//HintName: TestNamespace.Logger2.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class Logger2Registration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.Logger2 Creator();
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.Logger2), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.Logger2();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Logger2";
        metadata.Type = typeof(global::TestNamespace.Logger2);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.ILogger)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.Logger2>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
