//HintName: DynamicEventWrapper.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class DynamicEventWrapperRegistration
{
    static object Creator()
    {
        return RuntimeHelpers.GetUninitializedObject(typeof(global::DynamicEventWrapper));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DynamicEvent>k__BackingField")]
    extern static ref object Field1(global::DynamicEventWrapper @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::DynamicEventWrapper), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(object), "dynamicEvent");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve object dynamicEvent parameter of DynamicEventWrapper");
            return (container2, ctx2) =>
            {
                var res = new global::DynamicEventWrapper(Unsafe.As<object>(f0(container2, ctx2)));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "DynamicEventWrapper";
        metadata.Type = typeof(global::DynamicEventWrapper);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::DynamicEventWrapper>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "DynamicEvent",
                Type = typeof(object),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
