//HintName: BTDB.GenerateForAttribute.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;

namespace BTDB;

static file class GenerateForAttributeRegistration
{
    static object Creator()
    {
        return RuntimeHelpers.GetUninitializedObject(typeof(global::BTDB.GenerateForAttribute));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ConstructorParameters>k__BackingField")]
    extern static ref global::System.Type[] Field1(global::BTDB.GenerateForAttribute @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::BTDB.GenerateForAttribute), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::System.Type), "type");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve System.Type type parameter of BTDB.GenerateForAttribute");
            return (container2, ctx2) =>
            {
                var res = new global::BTDB.GenerateForAttribute(Unsafe.As<global::System.Type>(f0(container2, ctx2)));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "GenerateForAttribute";
        metadata.Type = typeof(global::BTDB.GenerateForAttribute);
        metadata.Namespace = "BTDB";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::BTDB.GenerateForAttribute>(metadata);
        metadata.Fields = new[]
        {
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "ConstructorParameters",
                Type = typeof(global::System.Type[]),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
        };
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
