//HintName: TestNamespace.ErrorHandler.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class ErrorHandlerRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.ErrorHandler), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::TestNamespace.ILogger), "key1");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve TestNamespace.ILogger logger parameter of TestNamespace.ErrorHandler");
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.ErrorHandler(Unsafe.As<global::TestNamespace.ILogger>(f0(container2, ctx2)));
                return res;
            };
        });
    }
}
