//HintName: Logger.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class LoggerRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::Logger Constr();
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Logger), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = Constr();
                return res;
            };
        });
    }
}
