//HintName: TestNamespace.ErrorHandler.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

static file class ErrorHandlerRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Logger>k__BackingField")]
    extern static ref global::TestNamespace.ILogger FieldRefLogger(global::TestNamespace.ErrorHandler @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.ErrorHandler), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::TestNamespace.ILogger), "Logger");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve TestNamespace.ILogger Logger property of TestNamespace.ErrorHandler");
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.ErrorHandler();
                FieldRefLogger(res) = Unsafe.As<global::TestNamespace.ILogger>(f0(container2, ctx2));
                return res;
            };
        });
    }
}
