//HintName: TestNamespace.Logger[int].g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class LoggerRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.Logger<int>), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(int), "a");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve int a parameter of TestNamespace.Logger<int>");
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.Logger<int>((int)(f0(container2, ctx2)));
                return res;
            };
        });
    }
}
