//HintName: TestNamespace.Factory.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612,CS0618 // Obsolete member/type
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class FactoryRegistration
{
    [ModuleInitializer]
    internal static void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.Factory), Factory);
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(Func<global::TestNamespace.Logger,global::TestNamespace.Logger>), Factory);
        static Func<global::BTDB.IOC.IContainer,global::BTDB.IOC.IResolvingCtx?,object>? Factory(global::BTDB.IOC.IContainer container, global::BTDB.IOC.ICreateFactoryCtx ctx)
        {
            using var resolvingCtxRestorer = ctx.ResolvingCtxRestorer();
            var hasResolvingCtx = ctx.HasResolvingCtx();
            var p0Idx = ctx.AddInstanceToCtx(typeof(global::TestNamespace.Logger), "logger");
            var nestedFactory = container.CreateFactory(ctx, typeof(global::TestNamespace.Logger), null);
            if (nestedFactory == null) return null;
            if (hasResolvingCtx)
            {
                return (c, r) => (global::TestNamespace.Logger p0) =>
                {
                    var p0Backup = r!.Exchange(p0Idx, p0);
                    try
                    {
                        return nestedFactory(c, r);
                    }
                    finally
                    {
                        r!.Set(p0Idx, p0Backup);
                    }
                };
            }
            else
            {
                var paramSize = ctx.GetParamSize();
                return (c, _) => (global::TestNamespace.Logger p0) =>
                {
                    var r = new global::BTDB.IOC.ResolvingCtx(paramSize);
                    r.Set(p0Idx, p0);
                    return nestedFactory(c, r);
                };
            }
        }
    }
}
