//HintName: TestNamespace.ErrorHandler.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class ErrorHandlerRegistration
{
    static object Creator()
    {
        return RuntimeHelpers.GetUninitializedObject(typeof(global::TestNamespace.ErrorHandler));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.ErrorHandler), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(int), "a");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve int a parameter of TestNamespace.ErrorHandler");
            var f1 = container.CreateFactory(ctx, typeof(int), "b");
            if (f1 == null) throw new global::System.ArgumentException("Cannot resolve int b parameter of TestNamespace.ErrorHandler");
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.ErrorHandler((int)(f0(container2, ctx2)), (int)(f1(container2, ctx2)));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ErrorHandler";
        metadata.Type = typeof(global::TestNamespace.ErrorHandler);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.IBetterLogger), typeof(global::TestNamespace.ILogger), typeof(global::TestNamespace.IErrorHandler)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.ErrorHandler>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
