//HintName: ErrorHandler.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ErrorHandlerRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::ErrorHandler Creator();
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::ErrorHandler), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::ILogger), "Key1");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve ILogger Logger property of ErrorHandler");
            return (container2, ctx2) =>
            {
                var res = new global::ErrorHandler();
                res.Logger = Unsafe.As<global::ILogger>(f0(container2, ctx2));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ErrorHandler";
        metadata.Type = typeof(global::ErrorHandler);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::ErrorHandler>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
