//HintName: TestNamespace.ConcreteHandler.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class ConcreteHandlerRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.ConcreteHandler Creator();
    public static class FieldAdapter1<TInput, TResult> where TInput: global::TestNamespace.IInput where TResult: global::TestNamespace.IResult
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CanStart>k__BackingField")]
        extern public static ref bool Field(global::TestNamespace.AbstractHandler<TInput, TResult> @this);
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.ConcreteHandler), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.ConcreteHandler();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ConcreteHandler";
        metadata.Type = typeof(global::TestNamespace.ConcreteHandler);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.IHandler<global::TestNamespace.ConcreteInput, global::TestNamespace.ConcreteResult>)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.ConcreteHandler>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CanStart",
                Type = typeof(bool),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref FieldAdapter1<global::TestNamespace.ConcreteInput, global::TestNamespace.ConcreteResult>.Field(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
