//HintName: TestNamespace.Logger[string].g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

static file class LoggerRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.Logger<string>), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(string), "a");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve string a parameter of TestNamespace.Logger<string>");
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.Logger<string>(Unsafe.As<string>(f0(container2, ctx2)));
                return res;
            };
        });
    }
}
