//HintName: TestNamespace.ErrorHandler.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class ErrorHandlerRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Logger>k__BackingField")]
    extern static ref global::TestNamespace.ILogger FieldRefLogger(global::TestNamespace.ErrorHandler @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.ErrorHandler), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::TestNamespace.ILogger), "Logger");
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.ErrorHandler();
                if (f0 != null) FieldRefLogger(res) = Unsafe.As<global::TestNamespace.ILogger>(f0(container2, ctx2));
                return res;
            };
        });
    }
}
