//HintName: TestNamespace.Logger.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

public partial class Logger
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.Logger Creator();
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.Logger), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(int), "A");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve int A property of TestNamespace.Logger");
            var f1 = container.CreateFactory(ctx, typeof(int), "B");
            if (f1 == null) throw new global::System.ArgumentException("Cannot resolve int B property of TestNamespace.Logger");
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.Logger();
                res.A = (int)(f0(container2, ctx2));
                res.B = (int)(f1(container2, ctx2));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Logger";
        metadata.Type = typeof(global::TestNamespace.Logger);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.ILogger)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.Logger>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
