//HintName: TestNamespace.Logger[int].g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class LoggerRegistration
{
    public class Activator<T>
    {
        public static object Creator()
        {
            return RuntimeHelpers.GetUninitializedObject(typeof(global::TestNamespace.Logger<int>));
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.Logger<int>), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(int), "a");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve int a parameter of TestNamespace.Logger<int>");
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.Logger<int>((int)(f0(container2, ctx2)));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Logger<int>";
        metadata.Type = typeof(global::TestNamespace.Logger<int>);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.ILogger)];
        metadata.Creator = &Activator<int>.Creator;
        var dummy = Unsafe.As<global::TestNamespace.Logger<int>>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
