//HintName: Sample3rdPartyLib.Class3rdPartyWithKeyedDependency.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace Sample3rdPartyLib;

[CompilerGenerated]
static file class Class3rdPartyWithKeyedDependencyRegistration
{
    static object Creator()
    {
        return RuntimeHelpers.GetUninitializedObject(typeof(global::Sample3rdPartyLib.Class3rdPartyWithKeyedDependency));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Sample3rdPartyLib.Class3rdPartyWithKeyedDependency), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::Sample3rdPartyLib.I3rdPartyInterface), "Key1");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve Sample3rdPartyLib.I3rdPartyInterface dependency parameter of Sample3rdPartyLib.Class3rdPartyWithKeyedDependency");
            return (container2, ctx2) =>
            {
                var res = new global::Sample3rdPartyLib.Class3rdPartyWithKeyedDependency(Unsafe.As<global::Sample3rdPartyLib.I3rdPartyInterface>(f0(container2, ctx2)));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Class3rdPartyWithKeyedDependency";
        metadata.Type = typeof(global::Sample3rdPartyLib.Class3rdPartyWithKeyedDependency);
        metadata.Namespace = "Sample3rdPartyLib";
        metadata.Implements = [typeof(global::Sample3rdPartyLib.I3rdPartyInterface)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::Sample3rdPartyLib.Class3rdPartyWithKeyedDependency>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
