//HintName: Sample3rdPartyLib.Class3rdPartyWithKeyedDependency.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace Sample3rdPartyLib;

[CompilerGenerated]
static file class Class3rdPartyWithKeyedDependencyRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Sample3rdPartyLib.Class3rdPartyWithKeyedDependency), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::Sample3rdPartyLib.I3rdPartyInterface), "Key1");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve Sample3rdPartyLib.I3rdPartyInterface dependency parameter of Sample3rdPartyLib.Class3rdPartyWithKeyedDependency");
            return (container2, ctx2) =>
            {
                var res = new global::Sample3rdPartyLib.Class3rdPartyWithKeyedDependency(Unsafe.As<global::Sample3rdPartyLib.I3rdPartyInterface>(f0(container2, ctx2)));
                return res;
            };
        });
    }
}
