//HintName: ErrorHandler.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

static file class ErrorHandlerRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::ErrorHandler), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(long), "bufferSize");
            return (container2, ctx2) =>
            {
                var res = new global::ErrorHandler(f0 != null ? ((long)f0(container2, ctx2)) : (long)(1099511627776));
                return res;
            };
        });
    }
}
