//HintName: ErrorHandler.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ErrorHandlerRegistration
{
    static object Creator()
    {
        return RuntimeHelpers.GetUninitializedObject(typeof(global::ErrorHandler));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::ErrorHandler), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(long), "bufferSize");
            return (container2, ctx2) =>
            {
                var res = new global::ErrorHandler(f0 != null ? ((long)f0(container2, ctx2)) : (long)(1099511627776));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ErrorHandler";
        metadata.Type = typeof(global::ErrorHandler);
        metadata.Namespace = "";
        metadata.Implements = [typeof(global::IErrorHandler)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::ErrorHandler>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
