//HintName: TestNamespace.MessageHandler.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class MessageHandlerRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.MessageHandler Creator();
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.MessageHandler), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.MessageHandler();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "MessageHandler";
        metadata.Type = typeof(global::TestNamespace.MessageHandler);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.IDispatcher)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.MessageHandler>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
        global::TestNamespace.IDispatcher.ConsumeHandlers.GetOrAddValueRef(typeof(global::TestNamespace.Message).TypeHandle.Value).ExecuteFactory = (global::BTDB.IOC.IContainer c) => {
           var nestedFactory = c.CreateFactory(typeof(global::TestNamespace.MessageHandler));
           return (container, message) =>
           {
               var res = nestedFactory(container, null);
               Unsafe.As<global::TestNamespace.MessageHandler>(res).Consume(Unsafe.As<global::TestNamespace.Message>(message));
               return null;
           };
        };
    }
}
