//HintName: BTDBTest.ObjInObjV2.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace BTDBTest;

[CompilerGenerated]
static file class ObjInObjV2Registration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::BTDBTest.ObjInObjV2 Creator();
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::BTDBTest.ObjInObjV2), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::BTDBTest.ObjInObjV2();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ObjInObjV2";
        metadata.Type = typeof(global::BTDBTest.ObjInObjV2);
        metadata.Namespace = "BTDBTest";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::BTDBTest.ObjInObjV2>(metadata);
        metadata.Fields = new global::BTDB.Serialization.FieldMetadata[]
        {
        };
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
