//HintName: TestNamespace.SomeType.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class SomeTypeRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.SomeType Creator();
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.SomeType), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.SomeType();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "SomeType";
        metadata.Type = typeof(global::TestNamespace.SomeType);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.ISomeType)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.SomeType>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
