//HintName: BTDBTest.IRowObjInObjV2Table.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
// Name: IRowObjInObjV2Table
// Field: Id ulong
//           PrimaryIndex: 1
// Field: OO global::BTDBTest.ObjInObjV2 reference

namespace BTDBTest;
[CompilerGenerated]
static file class IRowObjInObjV2TableRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
    }
}
