//HintName: CollectionRegistrations.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class CollectionRegistrations
{
    [ModuleInitializer]
    internal static void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.IDictionary<int, (string, string)>),
            ElementKeyType = typeof(int),
            ElementValueType = typeof((string, string)),
            Creator = &Create1,
            AdderKeyValue = &Add1
        });

        static object Create1(uint capacity)
        {
            return new global::System.Collections.Generic.Dictionary<int, (string, string)>((int)capacity);
        }

        static void Add1(object c, ref byte key, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.Dictionary<int, (string, string)>>(c).Add(Unsafe.As<byte, int>(ref key), Unsafe.As<byte, (string, string)>(ref value));
        }

        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.ISet<(string, int)>),
            ElementKeyType = typeof((string, int)),
            Creator = &Create2,
            Adder = &Add2
        });

        static object Create2(uint capacity)
        {
            return new global::System.Collections.Generic.HashSet<(string, int)>((int)capacity);
        }

        static void Add2(object c, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.HashSet<(string, int)>>(c).Add(Unsafe.As<byte, (string, int)>(ref value));
        }
    }
}
