//HintName: TestNamespace.CommunicationPiece.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class CommunicationPieceRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.CommunicationPiece Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Submitted>k__BackingField")]
    extern static ref global::TestNamespace.ArchiveNullableValue<global::System.DateTime?> Field1(global::TestNamespace.CommunicationPiece @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.CommunicationPiece), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.CommunicationPiece();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "CommunicationPiece";
        metadata.Type = typeof(global::TestNamespace.CommunicationPiece);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.CommunicationPiece>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Submitted",
                Type = typeof(global::TestNamespace.ArchiveNullableValue<global::System.DateTime?>),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
