//HintName: CollectionRegistrations.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class CollectionRegistrations
{
    struct DictEntry<TKey, TValue>
    {
        public uint HashCode;
        public int Next;
        public TKey Key;
        public TValue Value;
    }

    struct HashSetEntry<T>
    {
        public uint HashCode;
        public int Next;
        public T Value;
    }

    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        DictEntry<int,string> e1 = new();
        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.Dictionary<int, string>),
            ElementKeyType = typeof(int),
            ElementValueType = typeof(string),
            OffsetNext = (uint)Unsafe.ByteOffset(ref Unsafe.As<DictEntry<int,string>, byte>(ref e1),
                ref Unsafe.As<int, byte>(ref e1.Next)),
            OffsetKey = (uint)Unsafe.ByteOffset(ref Unsafe.As<DictEntry<int,string>, byte>(ref e1),
                ref Unsafe.As<int, byte>(ref e1.Key)),
            OffsetValue = (uint)Unsafe.ByteOffset(ref Unsafe.As<DictEntry<int,string>, byte>(ref e1),
                ref Unsafe.As<string, byte>(ref e1.Value)),
            SizeOfEntry = (uint)Unsafe.SizeOf<DictEntry<int,string>>(),
            Creator = &Create1,
            AdderKeyValue = &Add1,
            ODBCreator = &ODBCreate1
        });

        static object Create1(uint capacity)
        {
            return new global::System.Collections.Generic.Dictionary<int, string>((int)capacity);
        }

        static void Add1(object c, ref byte key, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.Dictionary<int, string>>(c).Add(Unsafe.As<byte, int>(ref key), Unsafe.As<byte, string>(ref value));
        }

        static object ODBCreate1(BTDB.ODBLayer.IInternalObjectDBTransaction tr, BTDB.ODBLayer.ODBDictionaryConfiguration config, ulong id)
        {
            return new BTDB.ODBLayer.ODBDictionary<int, string>(tr, config, id);
        }
    }
}
