//HintName: CollectionRegistrations.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class CollectionRegistrations
{
    struct DictEntry<TKey, TValue>
    {
        public uint HashCode;
        public int Next;
        public TKey Key;
        public TValue Value;
    }

    struct HashSetEntry<T>
    {
        public uint HashCode;
        public int Next;
        public T Value;
    }

    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        DictEntry<ulong,global::BTDBTest.ObjectDbEventSerializeTest.Item> e1 = new();
        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.IDictionary<ulong, global::BTDBTest.ObjectDbEventSerializeTest.Item>),
            ElementKeyType = typeof(ulong),
            ElementValueType = typeof(global::BTDBTest.ObjectDbEventSerializeTest.Item),
            OffsetNext = (uint)Unsafe.ByteOffset(ref Unsafe.As<DictEntry<ulong,global::BTDBTest.ObjectDbEventSerializeTest.Item>, byte>(ref e1),
                ref Unsafe.As<int, byte>(ref e1.Next)),
            OffsetKey = (uint)Unsafe.ByteOffset(ref Unsafe.As<DictEntry<ulong,global::BTDBTest.ObjectDbEventSerializeTest.Item>, byte>(ref e1),
                ref Unsafe.As<ulong, byte>(ref e1.Key)),
            OffsetValue = (uint)Unsafe.ByteOffset(ref Unsafe.As<DictEntry<ulong,global::BTDBTest.ObjectDbEventSerializeTest.Item>, byte>(ref e1),
                ref Unsafe.As<global::BTDBTest.ObjectDbEventSerializeTest.Item, byte>(ref e1.Value)),
            SizeOfEntry = (uint)Unsafe.SizeOf<DictEntry<ulong,global::BTDBTest.ObjectDbEventSerializeTest.Item>>(),
            Creator = &Create1,
            AdderKeyValue = &Add1,
            ODBCreator = &ODBCreate1
        });

        static object Create1(uint capacity)
        {
            return new global::System.Collections.Generic.Dictionary<ulong, global::BTDBTest.ObjectDbEventSerializeTest.Item>((int)capacity);
        }

        static void Add1(object c, ref byte key, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.Dictionary<ulong, global::BTDBTest.ObjectDbEventSerializeTest.Item>>(c).Add(Unsafe.As<byte, ulong>(ref key), Unsafe.As<byte, global::BTDBTest.ObjectDbEventSerializeTest.Item>(ref value));
        }

        static object ODBCreate1(BTDB.ODBLayer.IInternalObjectDBTransaction tr, BTDB.ODBLayer.ODBDictionaryConfiguration config, ulong id)
        {
            return new BTDB.ODBLayer.ODBDictionary<ulong, global::BTDBTest.ObjectDbEventSerializeTest.Item>(tr, config, id);
        }
    }
}
