//HintName: CollectionRegistrations.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class CollectionRegistrations
{
    [ModuleInitializer]
    internal static void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.List<global::TestNamespace.Person>),
            ElementKeyType = typeof(global::TestNamespace.Person),
            Creator = &Create1,
            Adder = &Add1
        });

        static object Create1(uint capacity)
        {
            return new global::System.Collections.Generic.List<global::TestNamespace.Person>((int)capacity);
        }

        static void Add1(object c, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.List<global::TestNamespace.Person>>(c).Add(Unsafe.As<byte, global::TestNamespace.Person>(ref value));
        }
    }
}
