//HintName: StackAllocationRegistrations.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable 612, 618, CS0649, CS8500
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class StackAllocationRegistrations
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterStackAllocator(typeof(int?), &Allocate1);
        static void Allocate1(ref byte ctx, ref nint ptr, delegate*<ref byte, void> chain)
            {
                int? value = default;
                ptr = (nint)Unsafe.AsPointer(ref value);
                chain(ref ctx);
                ptr = 0;
            }

    }
}
