//HintName: CollectionRegistrations.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class CollectionRegistrations
{
    [ModuleInitializer]
    internal static void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.IList<string>),
            ElementKeyType = typeof(string),
            Creator = &Create1,
            Adder = &Add1
        });

        static object Create1(uint capacity)
        {
            return new global::System.Collections.Generic.List<string>((int)capacity);
        }

        static void Add1(object c, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.List<string>>(c).Add(Unsafe.As<byte, string>(ref value));
        }

        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.IDictionary<int, global::System.Collections.Generic.IList<string>>),
            ElementKeyType = typeof(int),
            ElementValueType = typeof(global::System.Collections.Generic.IList<string>),
            Creator = &Create2,
            AdderKeyValue = &Add2
        });

        static object Create2(uint capacity)
        {
            return new global::System.Collections.Generic.Dictionary<int, global::System.Collections.Generic.IList<string>>((int)capacity);
        }

        static void Add2(object c, ref byte key, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.Dictionary<int, global::System.Collections.Generic.IList<string>>>(c).Add(Unsafe.As<byte, int>(ref key), Unsafe.As<byte, global::System.Collections.Generic.IList<string>>(ref value));
        }

        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.IReadOnlyList<string>),
            ElementKeyType = typeof(string),
            Creator = &Create3,
            Adder = &Add3
        });

        static object Create3(uint capacity)
        {
            return new global::System.Collections.Generic.List<string>((int)capacity);
        }

        static void Add3(object c, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.List<string>>(c).Add(Unsafe.As<byte, string>(ref value));
        }

        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.IReadOnlyDictionary<int, global::System.Collections.Generic.IReadOnlyList<string>>),
            ElementKeyType = typeof(int),
            ElementValueType = typeof(global::System.Collections.Generic.IReadOnlyList<string>),
            Creator = &Create4,
            AdderKeyValue = &Add4
        });

        static object Create4(uint capacity)
        {
            return new global::System.Collections.Generic.Dictionary<int, global::System.Collections.Generic.IReadOnlyList<string>>((int)capacity);
        }

        static void Add4(object c, ref byte key, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.Dictionary<int, global::System.Collections.Generic.IReadOnlyList<string>>>(c).Add(Unsafe.As<byte, int>(ref key), Unsafe.As<byte, global::System.Collections.Generic.IReadOnlyList<string>>(ref value));
        }

        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.IEnumerable<string>),
            ElementKeyType = typeof(string),
            Creator = &Create5,
            Adder = &Add5
        });

        static object Create5(uint capacity)
        {
            return new global::System.Collections.Generic.List<string>((int)capacity);
        }

        static void Add5(object c, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.List<string>>(c).Add(Unsafe.As<byte, string>(ref value));
        }

        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.ISet<string>),
            ElementKeyType = typeof(string),
            Creator = &Create6,
            Adder = &Add6
        });

        static object Create6(uint capacity)
        {
            return new global::System.Collections.Generic.HashSet<string>((int)capacity);
        }

        static void Add6(object c, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.HashSet<string>>(c).Add(Unsafe.As<byte, string>(ref value));
        }

        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.IReadOnlySet<string>),
            ElementKeyType = typeof(string),
            Creator = &Create7,
            Adder = &Add7
        });

        static object Create7(uint capacity)
        {
            return new global::System.Collections.Generic.HashSet<string>((int)capacity);
        }

        static void Add7(object c, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.HashSet<string>>(c).Add(Unsafe.As<byte, string>(ref value));
        }
    }
}
