//HintName: CollectionRegistrations.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class CollectionRegistrations
{
    struct DictEntry<TKey, TValue>
    {
        public uint HashCode;
        public int Next;
        public TKey Key;
        public TValue Value;
    }

    struct HashSetEntry<T>
    {
        public uint HashCode;
        public int Next;
        public T Value;
    }

    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        DictEntry<int,(string, string)> e1 = new();
        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.IDictionary<int, (string, string)>),
            ElementKeyType = typeof(int),
            ElementValueType = typeof((string, string)),
            OffsetNext = (uint)Unsafe.ByteOffset(ref Unsafe.As<DictEntry<int,(string, string)>, byte>(ref e1),
                ref Unsafe.As<int, byte>(ref e1.Next)),
            OffsetKey = (uint)Unsafe.ByteOffset(ref Unsafe.As<DictEntry<int,(string, string)>, byte>(ref e1),
                ref Unsafe.As<int, byte>(ref e1.Key)),
            OffsetValue = (uint)Unsafe.ByteOffset(ref Unsafe.As<DictEntry<int,(string, string)>, byte>(ref e1),
                ref Unsafe.As<(string, string), byte>(ref e1.Value)),
            SizeOfEntry = (uint)Unsafe.SizeOf<DictEntry<int,(string, string)>>(),
            Creator = &Create1,
            AdderKeyValue = &Add1,
            ODBCreator = &ODBCreate1
        });

        static object Create1(uint capacity)
        {
            return new global::System.Collections.Generic.Dictionary<int, (string, string)>((int)capacity);
        }

        static void Add1(object c, ref byte key, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.Dictionary<int, (string, string)>>(c).Add(Unsafe.As<byte, int>(ref key), Unsafe.As<byte, (string, string)>(ref value));
        }

        static object ODBCreate1(BTDB.ODBLayer.IInternalObjectDBTransaction tr, BTDB.ODBLayer.ODBDictionaryConfiguration config, ulong id)
        {
            return new BTDB.ODBLayer.ODBDictionary<int, (string, string)>(tr, config, id);
        }

        HashSetEntry<(string, int)> e2 = new();
        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.ISet<(string, int)>),
            ElementKeyType = typeof((string, int)),
            OffsetNext = (uint)Unsafe.ByteOffset(ref Unsafe.As<HashSetEntry<(string, int)>, byte>(ref e2),
                ref Unsafe.As<int, byte>(ref e2.Next)),
            OffsetKey = (uint)Unsafe.ByteOffset(ref Unsafe.As<HashSetEntry<(string, int)>, byte>(ref e2),
                ref Unsafe.As<(string, int), byte>(ref e2.Value)),
            SizeOfEntry = (uint)Unsafe.SizeOf<HashSetEntry<(string, int)>>(),
            Creator = &Create2,
            Adder = &Add2,
            ODBCreator = &ODBCreate2
        });

        static object Create2(uint capacity)
        {
            return new global::System.Collections.Generic.HashSet<(string, int)>((int)capacity);
        }

        static void Add2(object c, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.HashSet<(string, int)>>(c).Add(Unsafe.As<byte, (string, int)>(ref value));
        }

        static object ODBCreate2(BTDB.ODBLayer.IInternalObjectDBTransaction tr, BTDB.ODBLayer.ODBDictionaryConfiguration config, ulong id)
        {
            return new BTDB.ODBLayer.ODBSet<(string, int)>(tr, config, id);
        }
    }
}
