//HintName: StackAllocationRegistrations.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable 612, 618, CS0649, CS8500
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class StackAllocationRegistrations
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterStackAllocator(typeof((string, string)), &Allocate1);
        static void Allocate1(ref byte ctx, ref nint ptr, delegate*<ref byte, void> chain)
            {
                (string, string) value;
                ptr = (nint)(&value);
                chain(ref ctx);
                ptr = 0;
            }

        BTDB.Serialization.ReflectionMetadata.RegisterStackAllocator(typeof((string, int)), &Allocate2);
        static void Allocate2(ref byte ctx, ref nint ptr, delegate*<ref byte, void> chain)
            {
                (string, int) value;
                ptr = (nint)(&value);
                chain(ref ctx);
                ptr = 0;
            }
    }
}
