//HintName: CollectionRegistrations.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable 612, 618, CS0649
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class CollectionRegistrations
{
    struct DictEntry<TKey, TValue>
    {
        public uint HashCode;
        public int Next;
        public TKey Key;
        public TValue Value;
    }

    struct HashSetEntry<T>
    {
        public uint HashCode;
        public int Next;
        public T Value;
    }

    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        HashSetEntry<global::System.Enum> e1 = new();
        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.List<global::System.Enum>),
            ElementKeyType = typeof(global::System.Enum),
            OffsetNext = (uint)Unsafe.ByteOffset(ref Unsafe.As<HashSetEntry<global::System.Enum>, byte>(ref e1),
                ref Unsafe.As<int, byte>(ref e1.Next)),
            OffsetKey = (uint)Unsafe.ByteOffset(ref Unsafe.As<HashSetEntry<global::System.Enum>, byte>(ref e1),
                ref Unsafe.As<global::System.Enum, byte>(ref e1.Value)),
            SizeOfEntry = (uint)Unsafe.SizeOf<HashSetEntry<global::System.Enum>>(),
            Creator = &Create1,
            Adder = &Add1,
            ODBCreator = &ODBCreate1
        });

        static object Create1(uint capacity)
        {
            return new global::System.Collections.Generic.List<global::System.Enum>((int)capacity);
        }

        static void Add1(object c, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.List<global::System.Enum>>(c).Add(Unsafe.As<byte, global::System.Enum>(ref value));
        }

        static object ODBCreate1(BTDB.ODBLayer.IInternalObjectDBTransaction tr, BTDB.ODBLayer.ODBDictionaryConfiguration config, ulong id)
        {
            return new BTDB.ODBLayer.ODBSet<global::System.Enum>(tr, config, id);
        }
    }
}
