//HintName: TestNamespace.GenericClass[TestNamespace.SomeType].g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class GenericClassRegistration
{
    public class Activator<T> where T: global::TestNamespace.ISomeType, new()
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
        extern public static global::TestNamespace.GenericClass<T> Creator();
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Value>k__BackingField")]
        extern public static ref T Field1(global::TestNamespace.GenericClass<T> @this);
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.GenericClass<global::TestNamespace.SomeType>), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.GenericClass<global::TestNamespace.SomeType>();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "GenericClass<TestNamespace.SomeType>";
        metadata.Type = typeof(global::TestNamespace.GenericClass<global::TestNamespace.SomeType>);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [];
        metadata.Creator = &Activator<global::TestNamespace.SomeType>.Creator;
        var dummy = Unsafe.As<global::TestNamespace.GenericClass<global::TestNamespace.SomeType>>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Value",
                Type = typeof(global::TestNamespace.SomeType),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Activator<global::TestNamespace.SomeType>.Field1(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
