//HintName: TestNamespace.GenericClass[System.Enum].g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class GenericClassRegistration
{
    public class Activator<T>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
        extern public static global::TestNamespace.GenericClass<T> Creator();
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Value>k__BackingField")]
        extern public static ref T Field1(global::TestNamespace.GenericClass<T> @this);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Values>k__BackingField")]
        extern public static ref global::System.Collections.Generic.List<T> Field2(global::TestNamespace.GenericClass<T> @this);
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.GenericClass<global::System.Enum>), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.GenericClass<global::System.Enum>();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "GenericClass<System.Enum>";
        metadata.Type = typeof(global::TestNamespace.GenericClass<global::System.Enum>);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [];
        metadata.Creator = &Activator<global::System.Enum>.Creator;
        var dummy = Unsafe.As<global::TestNamespace.GenericClass<global::System.Enum>>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Value",
                Type = typeof(global::System.Enum),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Activator<global::System.Enum>.Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Values",
                Type = typeof(global::System.Collections.Generic.List<global::System.Enum>),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Activator<global::System.Enum>.Field2(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
