//HintName: BTDBTest.ObjectDbEventSerializeTest.IObjWithIDictionaryTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
// Name: IObjWithIDictionaryTable
// Field: TenantId uint
//           PrimaryIndex: 1
// Field: Dict global::System.Collections.Generic.IDictionary<ulong, global::BTDBTest.ObjectDbEventSerializeTest.Item> reference

namespace BTDBTest;
[CompilerGenerated]
static file class IObjWithIDictionaryTableRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
    }
}
