//HintName: BTDBTest.RowObjInObjV2.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace BTDBTest;

[CompilerGenerated]
static file class RowObjInObjV2Registration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::BTDBTest.RowObjInObjV2 Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    extern static ref ulong Field1(global::BTDBTest.RowObjInObjV2 @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OO>k__BackingField")]
    extern static ref global::BTDBTest.ObjInObjV2 Field2(global::BTDBTest.RowObjInObjV2 @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::BTDBTest.RowObjInObjV2), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::BTDBTest.RowObjInObjV2();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "RowObjInObjV2";
        metadata.Type = typeof(global::BTDBTest.RowObjInObjV2);
        metadata.Namespace = "BTDBTest";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::BTDBTest.RowObjInObjV2>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "OO",
                Type = typeof(global::BTDBTest.ObjInObjV2),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0];
        metadata.IndexOfInKeyValue = 1;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
