//HintName: TestNamespace.Person.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

static file class PersonRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.Person Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
    extern static ref string Field1(global::TestNamespace.Person @this);
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Name")]
    extern static void Setter1(global::TestNamespace.Person @this, string value);
    static void GenSetter1(object @this, object value)
    {
        Setter1(Unsafe.As<global::TestNamespace.Person>(@this), Unsafe.As<string>(value));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Age>k__BackingField")]
    extern static ref int Field2(global::TestNamespace.Person @this);
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Age")]
    extern static void Setter2(global::TestNamespace.Person @this, int value);
    static void GenSetter2(object @this, ref byte value)
    {
        Setter2(Unsafe.As<global::TestNamespace.Person>(@this), Unsafe.As<byte, int>(ref value));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.Person), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.Person();
                return res;
            };
        });
        var metadata = new BTDB.Serialization.ClassMetadata();
        metadata.Name = "Person";
        metadata.Type = typeof(global::TestNamespace.Person);
        metadata.Namespace = "TestNamespace";
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.Person>(metadata);
        metadata.Fields = new[]
        {
            new BTDB.Serialization.FieldMetadata
            {
                Name = "Name",
                Type = typeof(string),
                ByteOffset = BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
                PropObjSetter = &GenSetter1,
            },
            new BTDB.Serialization.FieldMetadata
            {
                Name = "Age",
                Type = typeof(int),
                ByteOffset = BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
                PropRefSetter = &GenSetter2,
            },
        };
        BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
