//HintName: TestNamespace.ProgramStrategyKey.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class ProgramStrategyKeyRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.ProgramStrategyKey Creator();
    public static class GetterAdapter1<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_CompanyId")]
        extern public static ulong Getter(global::TestNamespace.CompanyMapKeyBase<TKey> @this);
    }
    static void GenGetter1(object @this, ref byte value)
    {
        Unsafe.As<byte, ulong>(ref value) = GetterAdapter1<ulong>.Getter(Unsafe.As<global::TestNamespace.CompanyMapKeyBase<ulong>>(@this));
    }
    public static class SetterAdapter1<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_CompanyId")]
        extern public static void Setter(global::TestNamespace.CompanyMapKeyBase<TKey> @this, ulong value);
    }
    static void GenSetter1(object @this, ref byte value)
    {
        SetterAdapter1<ulong>.Setter(Unsafe.As<global::TestNamespace.CompanyMapKeyBase<ulong>>(@this), Unsafe.As<byte, ulong>(ref value));
    }
    public static class FieldAdapter2<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_id")]
        extern public static ref TKey Field(global::TestNamespace.CompanyMapKeyBase<TKey> @this);
    }
    public static class SetterAdapter2<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Id")]
        extern public static void Setter(global::TestNamespace.CompanyMapKeyBase<TKey> @this, TKey value);
    }
    static void GenSetter2(object @this, ref byte value)
    {
        SetterAdapter2<ulong>.Setter(Unsafe.As<global::TestNamespace.CompanyMapKeyBase<ulong>>(@this), Unsafe.As<byte, ulong>(ref value));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.ProgramStrategyKey), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.ProgramStrategyKey();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ProgramStrategyKey";
        metadata.Type = typeof(global::TestNamespace.ProgramStrategyKey);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.ProgramStrategyKey>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                PropRefGetter = &GenGetter1,
                PropRefSetter = &GenSetter1,
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref FieldAdapter2<ulong>.Field(dummy)),
                PropRefSetter = &GenSetter2,
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
