//HintName: TestNamespace.GenericClass[System.Enum].g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class GenericClassRegistration
{
    public class Activator<T>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
        extern public static global::TestNamespace.GenericClass<T> Creator();
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_Value")]
        extern public static T Getter1(global::TestNamespace.GenericClass<T> @this);
        public static void GenGetter1(object @this, ref byte value)
        {
            Unsafe.As<byte, T>(ref value) = Getter1(Unsafe.As<global::TestNamespace.GenericClass<T>>(@this));
        }
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Value")]
        extern public static void Setter1(global::TestNamespace.GenericClass<T> @this, T value);
        public static void GenSetter1(object @this, ref byte value)
        {
            Setter1(Unsafe.As<global::TestNamespace.GenericClass<T>>(@this), Unsafe.As<byte, T>(ref value));
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.GenericClass<global::System.Enum>), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.GenericClass<global::System.Enum>();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "GenericClass<System.Enum>";
        metadata.Type = typeof(global::TestNamespace.GenericClass<global::System.Enum>);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [];
        metadata.Creator = &Activator<global::System.Enum>.Creator;
        var dummy = Unsafe.As<global::TestNamespace.GenericClass<global::System.Enum>>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Value",
                Type = typeof(global::System.Enum),
                PropRefGetter = &Activator<global::System.Enum>.GenGetter1,
                PropRefSetter = &Activator<global::System.Enum>.GenSetter1,
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
