//HintName: TestNamespace.ArchiveNullableValue[System.DateTime_].g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class ArchiveNullableValueRegistration
{
    public class Activator<T>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
        extern public static global::TestNamespace.ArchiveNullableValue<T> Creator();
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Value>k__BackingField")]
        extern public static ref T Field1(global::TestNamespace.ArchiveNullableValue<T> @this);
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.ArchiveNullableValue<global::System.DateTime?>), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.ArchiveNullableValue<global::System.DateTime?>();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ArchiveNullableValue<System.DateTime?>";
        metadata.Type = typeof(global::TestNamespace.ArchiveNullableValue<global::System.DateTime?>);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [];
        metadata.Creator = &Activator<global::System.DateTime?>.Creator;
        var dummy = Unsafe.As<global::TestNamespace.ArchiveNullableValue<global::System.DateTime?>>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Value",
                Type = typeof(global::System.DateTime?),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Activator<global::System.DateTime?>.Field1(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
