//HintName: ConcreteKey.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ConcreteKeyRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::ConcreteKey Creator();
    public static class GetterAdapter1<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_CompanyId")]
        extern public static ulong Getter(global::Sample3rdPartyLib.SampleGenericBase<TKey> @this);
    }
    static void GenGetter1(object @this, ref byte value)
    {
        Unsafe.As<byte, ulong>(ref value) = GetterAdapter1<ulong>.Getter(Unsafe.As<global::Sample3rdPartyLib.SampleGenericBase<ulong>>(@this));
    }
    public static class SetterAdapter1<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_CompanyId")]
        extern public static void Setter(global::Sample3rdPartyLib.SampleGenericBase<TKey> @this, ulong value);
    }
    static void GenSetter1(object @this, ref byte value)
    {
        SetterAdapter1<ulong>.Setter(Unsafe.As<global::Sample3rdPartyLib.SampleGenericBase<ulong>>(@this), Unsafe.As<byte, ulong>(ref value));
    }
    public static class GetterAdapter2<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_Id")]
        extern public static TKey Getter(global::Sample3rdPartyLib.SampleGenericBase<TKey> @this);
    }
    static void GenGetter2(object @this, ref byte value)
    {
        Unsafe.As<byte, ulong>(ref value) = GetterAdapter2<ulong>.Getter(Unsafe.As<global::Sample3rdPartyLib.SampleGenericBase<ulong>>(@this));
    }
    public static class SetterAdapter2<TKey>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Id")]
        extern public static void Setter(global::Sample3rdPartyLib.SampleGenericBase<TKey> @this, TKey value);
    }
    static void GenSetter2(object @this, ref byte value)
    {
        SetterAdapter2<ulong>.Setter(Unsafe.As<global::Sample3rdPartyLib.SampleGenericBase<ulong>>(@this), Unsafe.As<byte, ulong>(ref value));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::ConcreteKey), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::ConcreteKey();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ConcreteKey";
        metadata.Type = typeof(global::ConcreteKey);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::ConcreteKey>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                PropRefGetter = &GenGetter1,
                PropRefSetter = &GenSetter1,
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                PropRefGetter = &GenGetter2,
                PropRefSetter = &GenSetter2,
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
