//HintName: TestNamespace.DerivedChild.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class DerivedChildRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.DerivedChild Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    extern static ref ulong Field1(global::TestNamespace.Child @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.DerivedChild), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.DerivedChild();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "DerivedChild";
        metadata.Type = typeof(global::TestNamespace.DerivedChild);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.IChild)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.DerivedChild>(metadata);
        metadata.Fields = new global::BTDB.Serialization.FieldMetadata[]
        {
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
        };
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
