//HintName: BTDBTest.ObjectDbEventSerializeTest.Item.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace BTDBTest;

[CompilerGenerated]
static file class ItemRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::BTDBTest.ObjectDbEventSerializeTest.Item Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    extern static ref ulong Field1(global::BTDBTest.ObjectDbEventSerializeTest.Item @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
    extern static ref string Field2(global::BTDBTest.ObjectDbEventSerializeTest.Item @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::BTDBTest.ObjectDbEventSerializeTest.Item), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::BTDBTest.ObjectDbEventSerializeTest.Item();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Item";
        metadata.Type = typeof(global::BTDBTest.ObjectDbEventSerializeTest.Item);
        metadata.Namespace = "BTDBTest";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::BTDBTest.ObjectDbEventSerializeTest.Item>(metadata);
        metadata.Fields = new global::BTDB.Serialization.FieldMetadata[]
        {
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Name",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        };
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
