//HintName: BTDBTest.ObjectDbEventSerializeTest.ObjWithIDictionary.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace BTDBTest;

[CompilerGenerated]
static file class ObjWithIDictionaryRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::BTDBTest.ObjectDbEventSerializeTest.ObjWithIDictionary Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TenantId>k__BackingField")]
    extern static ref uint Field1(global::BTDBTest.ObjectDbEventSerializeTest.ObjWithIDictionary @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Dict>k__BackingField")]
    extern static ref global::System.Collections.Generic.IDictionary<ulong, global::BTDBTest.ObjectDbEventSerializeTest.Item> Field2(global::BTDBTest.ObjectDbEventSerializeTest.ObjWithIDictionary @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::BTDBTest.ObjectDbEventSerializeTest.ObjWithIDictionary), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::BTDBTest.ObjectDbEventSerializeTest.ObjWithIDictionary();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ObjWithIDictionary";
        metadata.Type = typeof(global::BTDBTest.ObjectDbEventSerializeTest.ObjWithIDictionary);
        metadata.Namespace = "BTDBTest";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::BTDBTest.ObjectDbEventSerializeTest.ObjWithIDictionary>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "TenantId",
                Type = typeof(uint),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Dict",
                Type = typeof(global::System.Collections.Generic.IDictionary<ulong, global::BTDBTest.ObjectDbEventSerializeTest.Item>),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0];
        metadata.IndexOfInKeyValue = 1;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
