//HintName: CollectionRegistrations.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;
[CompilerGenerated]
static file class CollectionRegistrations
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterCollection(new()
        {
            Type = typeof(global::System.Collections.Generic.Dictionary<int, string>),
            ElementKeyType = typeof(int),
            ElementValueType = typeof(string),
            Creator = &Create1,
            AdderKeyValue = &Add1
        });

        static object Create1(uint capacity)
        {
            return new global::System.Collections.Generic.Dictionary<int, string>((int)capacity);
        }

        static void Add1(object c, ref byte key, ref byte value)
        {
            Unsafe.As<global::System.Collections.Generic.Dictionary<int, string>>(c).Add(Unsafe.As<byte, int>(ref key), Unsafe.As<byte, string>(ref value));
        }
    }
}
