//HintName: Entity.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class EntityRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::Entity Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_TenantId")]
    extern static ulong Getter1(global::IBaseEntity @this);
    static void GenGetter1(object @this, ref byte value)
    {
        Unsafe.As<byte, ulong>(ref value) = Getter1(Unsafe.As<global::IBaseEntity>(@this));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_TenantId")]
    extern static void Setter1(global::IBaseEntity @this, ulong value);
    static void GenSetter1(object @this, ref byte value)
    {
        Setter1(Unsafe.As<global::IBaseEntity>(@this), Unsafe.As<byte, ulong>(ref value));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_Name")]
    extern static string Getter2(global::IEntity @this);
    static void GenGetter2(object @this, ref byte value)
    {
        Unsafe.As<byte, string>(ref value) = Getter2(Unsafe.As<global::IEntity>(@this));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Name")]
    extern static void Setter2(global::IEntity @this, string value);
    static void GenSetter2(object @this, ref byte value)
    {
        Setter2(Unsafe.As<global::IEntity>(@this), Unsafe.As<byte, string>(ref value));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Entity), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::Entity();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Entity";
        metadata.Type = typeof(global::Entity);
        metadata.Namespace = "";
        metadata.Implements = [typeof(global::IEntity), typeof(global::ILeftEntity), typeof(global::IRightEntity), typeof(global::IBaseEntity)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::Entity>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "TenantId",
                Type = typeof(ulong),
                PropRefGetter = &GenGetter1,
                PropRefSetter = &GenSetter1,
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Name",
                Type = typeof(string),
                PropRefGetter = &GenGetter2,
                PropRefSetter = &GenSetter2,
            },
        ];
        metadata.OnSerialize = &OnSerialize;
        static void OnSerialize(object @this)
        {
            Unsafe.As<global::IBaseEntity>(@this).BaseSerialize();
        }
        metadata.OnBeforeRemoveFactory = container =>
        {
            return (transaction, value) =>
            {
                var val = Unsafe.As<global::Entity>(value);
                var res = false;
                Unsafe.As<global::IEntity>(value).BeforeRemove();
                return res;
            };
        };
        metadata.PrimaryKeyFields = [0];
        metadata.IndexOfInKeyValue = 1;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
