//HintName: TestNamespace.IFileTable[TestNamespace.DownloadSectionFile].g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IFileTable
// Field: UploadGuid string reference
// Field: Id ulong
//           PrimaryIndex: 0
// Field: FileName string reference

namespace TestNamespace;
[CompilerGenerated]
file class IFileTableRegistration
{
    public class ImplFileTable : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.DownloadSectionFile>, global::TestNamespace.IFileTable<global::TestNamespace.DownloadSectionFile>
    {
        public ImplFileTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::TestNamespace.DownloadSectionFile global::TestNamespace.IFileTable<global::TestNamespace.DownloadSectionFile>.FindByIdOrDefault(ulong id)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(id);
            return base.FindByIdOrDefault<global::TestNamespace.DownloadSectionFile>(writer.GetSpan(), false, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.IFileTable<global::TestNamespace.DownloadSectionFile>),
            info => { return transaction => new ImplFileTable(transaction, info); },
            [typeof(global::TestNamespace.DownloadSectionFile)]);
    }
}
