//HintName: TestNamespace.IFakeTeamVisibilityTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IFakeTeamVisibilityTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: TeamId ulong
//           PrimaryIndex: 2
// Field: ItemId ulong
//           PrimaryIndex: 3
//           SecondaryIndex Item: 0 IncludePrimaryKeyOrder 1

namespace BTDB.GeneratedRelations;
[CompilerGenerated]
file class IFakeTeamVisibilityTableRegistration
{
    [Obsolete("BTDB generated relation implementation type is for BTDB internal use only.")]
    public class ImplFakeTeamVisibilityTable : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.FakeTeamVisibility>, global::TestNamespace.IFakeTeamVisibilityTable
    {
        public ImplFakeTeamVisibilityTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::TestNamespace.FakeTeamVisibility global::TestNamespace.ITeamVisibilityTable<global::TestNamespace.FakeTeamVisibility, ulong>.FindByIdOrDefault(ulong companyId, ulong teamId, ulong itemId)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            writer.WriteVUInt64(teamId);
            writer.WriteVUInt64(itemId);
            return base.FindByIdOrDefault<global::TestNamespace.FakeTeamVisibility>(writer.GetSpan(), false, 0);
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::TestNamespace.FakeTeamVisibility> global::TestNamespace.ITeamVisibilityTable<global::TestNamespace.FakeTeamVisibility, ulong>.ListById(ulong companyId, ulong teamId)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            writer.WriteVUInt64(teamId);
            return new global::BTDB.ODBLayer.RelationAdvancedEnumerator<global::TestNamespace.FakeTeamVisibility>(this, writer.GetSpan(), 0);
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::TestNamespace.FakeTeamVisibility> global::TestNamespace.ITeamVisibilityTable<global::TestNamespace.FakeTeamVisibility, ulong>.ListByItem(ulong companyId, ulong itemId)
        {
            var remappedSecondaryKeyIndex = RemapPrimeSK(0u);
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationSKPrefix(ref writer, remappedSecondaryKeyIndex);
            writer.WriteVUInt64(companyId);
            writer.WriteVUInt64(itemId);
            return new global::BTDB.ODBLayer.RelationAdvancedSecondaryKeyEnumerator<global::TestNamespace.FakeTeamVisibility>(this, writer.GetSpan(), remappedSecondaryKeyIndex, 0);
        }

        [SkipLocalsInit]
        int global::TestNamespace.ITeamVisibilityTable<global::TestNamespace.FakeTeamVisibility, ulong>.RemoveById(ulong companyId, ulong teamId)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            writer.WriteVUInt64(teamId);
            return (int)base.RemoveByPrimaryKeyPrefix(writer.GetSpan());
        }

        [SkipLocalsInit]
        int global::TestNamespace.ITeamVisibilityTable<global::TestNamespace.FakeTeamVisibility, ulong>.RemoveById(ulong companyId, ulong teamId, ulong itemId)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            writer.WriteVUInt64(teamId);
            writer.WriteVUInt64(itemId);
            return (int)base.RemoveByPrimaryKeyPrefix(writer.GetSpan());
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.IFakeTeamVisibilityTable),
            info => { return transaction => new ImplFakeTeamVisibilityTable(transaction, info); },
            [typeof(global::TestNamespace.FakeTeamVisibility)]);
    }
}
