//HintName: IDeliveryRuleTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
// Name: IDeliveryRuleTable
// Field: Activities global::System.Collections.Generic.IList<global::Activity> reference
// Field: Id ulong
//           PrimaryIndex: 1
// Field: Status int
[CompilerGenerated]
static file class IDeliveryRuleTableRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
    }
}
