//HintName: CompanyUserRoleIteration.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class CompanyUserRoleIterationRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::CompanyUserRoleIteration Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
    extern static ref ulong Field1(global::CompanyUserRoleIteration @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RoleId>k__BackingField")]
    extern static ref ulong Field2(global::CompanyUserRoleIteration @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::CompanyUserRoleIteration), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::CompanyUserRoleIteration();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "CompanyUserRoleIteration";
        metadata.Type = typeof(global::CompanyUserRoleIteration);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::CompanyUserRoleIteration>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "UserId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "RoleId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
