//HintName: IProductTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IProductTable
// Field: Id ulong
//           PrimaryIndex: 1
// Field: Name string reference
[CompilerGenerated]
file class IProductTableRegistration
{
    public class ImplProductTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Product>, global::IProductTable
    {
        public ImplProductTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::Product global::IProductTable.FirstByIdOrDefault(BTDB.ODBLayer.Constraint<ulong> id)
        {
            var c_c = new ConstraintInfo[1];
            c_c[0].Constraint = id;
            return FirstByPrimaryKey<global::Product>(0, c_c, null, null, true);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IProductTable),
            info => { return transaction => new ImplProductTable(transaction, info); },
            [typeof(global::Product)]);
    }
}
