//HintName: IBitmapTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IBitmapTable
// Field: Id ulong
//           PrimaryIndex: 1
// Field: Bits global::BTDB.ODBLayer.IRoaringBitmap reference

namespace BTDB.GeneratedRelations;
[CompilerGenerated]
file class IBitmapTableRegistration
{
    [Obsolete("BTDB generated relation implementation type is for BTDB internal use only.")]
    public class ImplBitmapTable : global::BTDB.ODBLayer.RelationDBManipulator<global::BitmapRow>, global::IBitmapTable
    {
        public ImplBitmapTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        void global::IBitmapTable.Insert(global::BitmapRow row)
        {
            base.InsertUniqueOrThrow(row);
        }

        [SkipLocalsInit]
        global::BitmapRow global::IBitmapTable.FindById(ulong id)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(id);
            return base.FindByIdOrDefault<global::BitmapRow>(writer.GetSpan(), true, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IBitmapTable),
            info => { return transaction => new ImplBitmapTable(transaction, info); },
            [typeof(global::BitmapRow)]);
    }
}
