//HintName: Gmc.Cloud.Processing.Job.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace Gmc.Cloud.Processing;

[CompilerGenerated]
static file class JobRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::Gmc.Cloud.Processing.Job Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompanyId>k__BackingField")]
    extern static ref ulong Field1(global::Gmc.Cloud.Processing.Job @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
    extern static ref global::Infrastructure.Impress.Status Field2(global::Gmc.Cloud.Processing.Job @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Gmc.Cloud.Processing.Job), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::Gmc.Cloud.Processing.Job();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Job";
        metadata.Type = typeof(global::Gmc.Cloud.Processing.Job);
        metadata.Namespace = "Gmc.Cloud.Processing";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::Gmc.Cloud.Processing.Job>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Status",
                Type = typeof(global::Infrastructure.Impress.Status),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1];
        metadata.IndexOfInKeyValue = 2;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
