//HintName: TestNamespace.Person.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class PersonRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.Person Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParentId>k__BackingField")]
    extern static ref int Field1(global::TestNamespace.Person @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PersonId>k__BackingField")]
    extern static ref int Field2(global::TestNamespace.Person @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
    extern static ref string Field3(global::TestNamespace.Person @this);
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_LowerCaseName")]
    extern static string Getter4(global::TestNamespace.Person @this);
    static void GenGetter4(object @this, ref byte value)
    {
        Unsafe.As<byte, string>(ref value) = Getter4(Unsafe.As<global::TestNamespace.Person>(@this));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
    extern static ref string Field5(global::TestNamespace.Person @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.Person), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.Person();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Person";
        metadata.Type = typeof(global::TestNamespace.Person);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.Person>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "ParentId",
                Type = typeof(int),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "PersonId",
                Type = typeof(int),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Name",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "LowerCaseName",
                Type = typeof(string),
                PropRefGetter = &GenGetter4,
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Description",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field5(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
