//HintName: TestNamespace.ICompanyRecordTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: ICompanyRecordTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: Id ulong
//           PrimaryIndex: 2

namespace BTDB.GeneratedRelations;
[CompilerGenerated]
file class ICompanyRecordTableRegistration
{
    [Obsolete("BTDB generated relation implementation type is for BTDB internal use only.")]
    public class ImplCompanyRecordTable : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.CompanyRecord>, global::TestNamespace.ICompanyRecordTable
    {
        public ImplCompanyRecordTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.ICompanyRecordTable),
            info => { return transaction => new ImplCompanyRecordTable(transaction, info); },
            [typeof(global::TestNamespace.CompanyRecord)]);
    }
}
