//HintName: IContractTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IContractTable
// Field: Id ulong
//           PrimaryIndex: 1
// Field: Name string reference
[CompilerGenerated]
file class IContractTableRegistration
{
    public class ImplContractTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Contract>, global::IContractTable
    {
        public ImplContractTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::Contract global::IContractTable.FindById(ulong id)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(id);
            return base.FindByIdOrDefault<global::Contract>(writer.GetSpan(), true, 0);
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::Contract> global::IContractTable.ListById()
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            return new global::BTDB.ODBLayer.RelationAdvancedEnumerator<global::Contract>(this, writer.GetSpan(), 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IContractTable),
            info => { return transaction => new ImplContractTable(transaction, info); },
            [typeof(global::Contract)]);
    }
}
