//HintName: LazyUlongListRow.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class LazyUlongListRowRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::LazyUlongListRow Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    extern static ref ulong Field1(global::LazyUlongListRow @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Values>k__BackingField")]
    extern static ref global::BTDB.ODBLayer.ILazyUlongList Field2(global::LazyUlongListRow @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::LazyUlongListRow), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::LazyUlongListRow();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "LazyUlongListRow";
        metadata.Type = typeof(global::LazyUlongListRow);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::LazyUlongListRow>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Values",
                Type = typeof(global::BTDB.ODBLayer.ILazyUlongList),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0];
        metadata.IndexOfInKeyValue = 1;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
