//HintName: IThingWithSKTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IThingWithSKTable
// Field: Tenant ulong
//           PrimaryIndex: 1
// Field: Name string reference
//           PrimaryIndex: 2
//           SecondaryIndex Name: 1
// Field: Age uint
//           SecondaryIndex Name: 2
[CompilerGenerated]
file class IThingWithSKTableRegistration
{
    public class ImplThingWithSKTable : global::BTDB.ODBLayer.RelationDBManipulator<global::ThingWithSK>, global::IThingWithSKTable
    {
        public ImplThingWithSKTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::ThingWithSK> global::IThingWithSKTable.ScanByName(BTDB.ODBLayer.Constraint<string> name, BTDB.ODBLayer.Constraint<ulong> age, BTDB.ODBLayer.Constraint<ulong> tenant)
        {
            var c_c = new ConstraintInfo[3];
            c_c[0].Constraint = name;
            c_c[1].Constraint = age;
            c_c[2].Constraint = tenant;
            return ScanBySecondaryKeyPrefix<global::ThingWithSK>(0, c_c, 0u);
        }

        [SkipLocalsInit]
        ulong global::IThingWithSKTable.GatherByName(System.Collections.Generic.List<ThingWithSK> target, long skip, long take, BTDB.ODBLayer.Constraint<string> name, BTDB.ODBLayer.Constraint<ulong> age, BTDB.ODBLayer.IOrderer[] orderers)
        {
            var c_c = new ConstraintInfo[2];
            c_c[0].Constraint = name;
            c_c[1].Constraint = age;
            return GatherBySecondaryKey(0, c_c, target, skip, take, 0u, orderers);
        }

        [SkipLocalsInit]
        global::ThingWithSK global::IThingWithSKTable.FirstByNameOrDefault(BTDB.ODBLayer.Constraint<string> name, BTDB.ODBLayer.Constraint<ulong> age, BTDB.ODBLayer.IOrderer[] orderers)
        {
            var c_c = new ConstraintInfo[2];
            c_c[0].Constraint = name;
            c_c[1].Constraint = age;
            return FirstBySecondaryKey<global::ThingWithSK>(0, c_c, 0u, orderers, true);
        }

        [SkipLocalsInit]
        global::ThingWithSK global::IThingWithSKTable.FirstByName(BTDB.ODBLayer.Constraint<string> name, BTDB.ODBLayer.Constraint<ulong> age, BTDB.ODBLayer.IOrderer[] orderers)
        {
            var c_c = new ConstraintInfo[2];
            c_c[0].Constraint = name;
            c_c[1].Constraint = age;
            return FirstBySecondaryKey<global::ThingWithSK>(0, c_c, 0u, orderers, false);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IThingWithSKTable),
            info => { return transaction => new ImplThingWithSKTable(transaction, info); },
            [typeof(global::ThingWithSK)]);
    }
}
