//HintName: TestNamespace.ICredentialsTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: ICredentialsTable
// Field: ConnectorId ulong
//           PrimaryIndex: 1
// Field: CompanyId ulong
//           PrimaryIndex: 2
// Field: Domain string reference
//           PrimaryIndex: 3
// Field: Name string reference

namespace TestNamespace;
[CompilerGenerated]
file class ICredentialsTableRegistration
{
    public class ImplCredentialsTable : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.Credentials>, global::TestNamespace.ICredentialsTable
    {
        public ImplCredentialsTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        bool global::TestNamespace.ICredentialsTable.Contains(ulong connectorId, ulong companyId, string? domain)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(connectorId);
            writer.WriteVUInt64(companyId);
            writer.WriteStringOrdered(domain);
            return base.Contains(writer.GetSpan());
        }

        [SkipLocalsInit]
        global::TestNamespace.Credentials? global::TestNamespace.ICredentialsTable.FindByIdOrDefault(ulong connectorId, ulong companyId, string? domain)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(connectorId);
            writer.WriteVUInt64(companyId);
            writer.WriteStringOrdered(domain);
            return base.FindByIdOrDefault<global::TestNamespace.Credentials>(writer.GetSpan(), false, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.ICredentialsTable),
            info => { return transaction => new ImplCredentialsTable(transaction, info); },
            [typeof(global::TestNamespace.Credentials)]);
    }
}
