//HintName: ContainsKeyTypes.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ContainsKeyTypesRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::ContainsKeyTypes Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
    extern static ref string Field1(global::ContainsKeyTypes @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Duration>k__BackingField")]
    extern static ref global::System.TimeSpan Field2(global::ContainsKeyTypes @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Address>k__BackingField")]
    extern static ref global::System.Net.IPAddress Field3(global::ContainsKeyTypes @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ApiVersion>k__BackingField")]
    extern static ref global::System.Version Field4(global::ContainsKeyTypes @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Tags>k__BackingField")]
    extern static ref global::Microsoft.Extensions.Primitives.StringValues Field5(global::ContainsKeyTypes @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Names>k__BackingField")]
    extern static ref global::System.Collections.Generic.List<string> Field6(global::ContainsKeyTypes @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Counters>k__BackingField")]
    extern static ref global::System.Collections.Generic.List<ulong> Field7(global::ContainsKeyTypes @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::ContainsKeyTypes), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::ContainsKeyTypes();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ContainsKeyTypes";
        metadata.Type = typeof(global::ContainsKeyTypes);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::ContainsKeyTypes>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Name",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Duration",
                Type = typeof(global::System.TimeSpan),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Address",
                Type = typeof(global::System.Net.IPAddress),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "ApiVersion",
                Type = typeof(global::System.Version),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field4(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Tags",
                Type = typeof(global::Microsoft.Extensions.Primitives.StringValues),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field5(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Names",
                Type = typeof(global::System.Collections.Generic.List<string>),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field6(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Counters",
                Type = typeof(global::System.Collections.Generic.List<ulong>),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field7(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1, 2, 3, 4, 5, 6];
        metadata.IndexOfInKeyValue = 7;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
