//HintName: Item.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ItemRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::Item Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompanyId>k__BackingField")]
    extern static ref ulong Field1(global::Item @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Queue>k__BackingField")]
    extern static ref string Field2(global::Item @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ItemId>k__BackingField")]
    extern static ref Guid Field3(global::Item @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Priority>k__BackingField")]
    extern static ref int Field4(global::Item @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LockDeadline>k__BackingField")]
    extern static ref DateTime Field5(global::Item @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Item), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::Item();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Item";
        metadata.Type = typeof(global::Item);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::Item>(metadata);
        metadata.Fields = new global::BTDB.Serialization.FieldMetadata[]
        {
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Queue",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "ItemId",
                Type = typeof(Guid),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Priority",
                Type = typeof(int),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field4(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "LockDeadline",
                Type = typeof(DateTime),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field5(dummy)),
            },
        };
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
