//HintName: IDocumentTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IDocumentTable
// Field: TenantId ulong
//           PrimaryIndex: 1
// Field: Key string reference
//           PrimaryIndex: 2
// Field: Value string reference
[CompilerGenerated]
file class IDocumentTableRegistration
{
    public class ImplDocumentTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Document>, global::IDocumentTable
    {
        public ImplDocumentTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        (ulong Count, ulong KeySizes, ulong ValueSizes) global::IDocumentTable.RemoveWithSizesById(BTDB.ODBLayer.Constraint<ulong> tenantId, BTDB.ODBLayer.Constraint<string> key)
        {
            var c_c = new ConstraintInfo[2];
            c_c[0].Constraint = tenantId;
            c_c[1].Constraint = key;
            return base.RemoveWithSizesByPrimaryKey(c_c);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IDocumentTable),
            info => { return transaction => new ImplDocumentTable(transaction, info); },
            [typeof(global::Document)]);
    }
}
