//HintName: IVariantTestTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
// Name: IVariantTestTable
// Field: Id ulong
//           PrimaryIndex: 1
// Field: Name string reference
// Field: Age int
[CompilerGenerated]
static file class IVariantTestTableRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
    }
}
