//HintName: IPersonTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IPersonTable
// Field: TenantId ulong
//           PrimaryIndex: 1
// Field: Id ulong
//           PrimaryIndex: 2
// Field: Name string reference
// Field: Secret global::BTDB.Encrypted.EncryptedString reference
[CompilerGenerated]
file class IPersonTableRegistration
{
    public class ImplPersonTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Person>, global::IPersonTable
    {
        public ImplPersonTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        bool global::IPersonTable.UpdateById(ulong tenantId, ulong id)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            var lenOfPkWoInKeyValues = 0;
            writer.WriteVUInt64(tenantId);
            writer.WriteVUInt64(id);
            var keyBytes = writer.GetScopedSpanAndReset();
            var updated = base.UpdateByIdInKeyValues(keyBytes, lenOfPkWoInKeyValues, false);
            return updated;
        }

        [SkipLocalsInit]
        bool global::IPersonTable.UpdateById(ulong tenantId, ulong id, string name)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            var lenOfPkWoInKeyValues = 0;
            writer.WriteVUInt64(tenantId);
            writer.WriteVUInt64(id);
            var keyBytes = writer.GetScopedSpanAndReset();
            var oldValueBytes = default(global::System.ReadOnlySpan<byte>);
            var updated = base.UpdateByIdStart(keyBytes, ref writer, ref oldValueBytes, lenOfPkWoInKeyValues, false);
            if (!updated) return false;
            global::BTDB.ODBLayer.DBWriterCtx? valueCtx = null;
            global::BTDB.ODBLayer.DBReaderCtx? readerCtx = null;
            unsafe
            {
                fixed (byte* _ = oldValueBytes)
                {
                    var reader = global::BTDB.StreamLayer.MemReader.CreateFromPinnedSpan(oldValueBytes);
                    reader.SkipVUInt32();
                    uint memoPos = 0;
                    var copyMode = false;
                    var valueFields = ValueFields;
                    for (var valueFieldIndex = 0; valueFieldIndex < valueFields.Length; valueFieldIndex++)
                    {
                        var valueField = valueFields[valueFieldIndex];
                        if (valueField.Computed) continue;
                        var paramIndex = -1;
                        if (string.Equals(valueField.Name, "name", StringComparison.OrdinalIgnoreCase))
                        {
                            paramIndex = 0;
                        }
                        var newCopyMode = paramIndex == -1;
                        if (copyMode != newCopyMode)
                        {
                            if (newCopyMode)
                            {
                                memoPos = (uint)reader.GetCurrentPositionWithoutController();
                            }
                            else
                            {
                                reader.CopyFromPosToWriter(memoPos, ref writer);
                            }
                            copyMode = newCopyMode;
                        }
                        var handler = valueField.Handler!;
                        if (!newCopyMode)
                        {
                            switch (paramIndex)
                            {
                                case 0:
                                {
                                    var save = handler.Save(typeof(string), Transaction.Owner.TypeConverterFactory);
                                    if (handler.NeedsCtx())
                                    {
                                        valueCtx ??= new global::BTDB.ODBLayer.DBWriterCtx(Transaction);
                                    }
                                    save(ref writer, valueCtx, ref Unsafe.As<string, byte>(ref name));
                                    break;
                                }
                            }
                        }
                        if (handler.NeedsCtx())
                        {
                            readerCtx ??= new global::BTDB.ODBLayer.DBReaderCtx(Transaction);
                            handler.Skip(ref reader, readerCtx);
                        }
                        else
                        {
                            handler.Skip(ref reader, null);
                        }
                    }
                    if (copyMode)
                    {
                        reader.CopyFromPosToWriter(memoPos, ref writer);
                    }
                }
            }
            base.UpdateByIdFinish(keyBytes, oldValueBytes, writer.GetSpan());
            return true;
        }

        [SkipLocalsInit]
        void global::IPersonTable.UpdateByIdSecret(ulong tenantId, ulong id, string secret)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            var lenOfPkWoInKeyValues = 0;
            writer.WriteVUInt64(tenantId);
            writer.WriteVUInt64(id);
            var keyBytes = writer.GetScopedSpanAndReset();
            var oldValueBytes = default(global::System.ReadOnlySpan<byte>);
            _ = base.UpdateByIdStart(keyBytes, ref writer, ref oldValueBytes, lenOfPkWoInKeyValues, true);
            global::BTDB.ODBLayer.DBWriterCtx? valueCtx = null;
            global::BTDB.ODBLayer.DBReaderCtx? readerCtx = null;
            unsafe
            {
                fixed (byte* _ = oldValueBytes)
                {
                    var reader = global::BTDB.StreamLayer.MemReader.CreateFromPinnedSpan(oldValueBytes);
                    reader.SkipVUInt32();
                    uint memoPos = 0;
                    var copyMode = false;
                    var valueFields = ValueFields;
                    for (var valueFieldIndex = 0; valueFieldIndex < valueFields.Length; valueFieldIndex++)
                    {
                        var valueField = valueFields[valueFieldIndex];
                        if (valueField.Computed) continue;
                        var paramIndex = -1;
                        if (string.Equals(valueField.Name, "secret", StringComparison.OrdinalIgnoreCase))
                        {
                            paramIndex = 0;
                        }
                        var newCopyMode = paramIndex == -1;
                        if (copyMode != newCopyMode)
                        {
                            if (newCopyMode)
                            {
                                memoPos = (uint)reader.GetCurrentPositionWithoutController();
                            }
                            else
                            {
                                reader.CopyFromPosToWriter(memoPos, ref writer);
                            }
                            copyMode = newCopyMode;
                        }
                        var handler = valueField.Handler!;
                        if (!newCopyMode)
                        {
                            switch (paramIndex)
                            {
                                case 0:
                                {
                                    var save = handler.Save(typeof(string), Transaction.Owner.TypeConverterFactory);
                                    if (handler.NeedsCtx())
                                    {
                                        valueCtx ??= new global::BTDB.ODBLayer.DBWriterCtx(Transaction);
                                    }
                                    save(ref writer, valueCtx, ref Unsafe.As<string, byte>(ref secret));
                                    break;
                                }
                            }
                        }
                        if (handler.NeedsCtx())
                        {
                            readerCtx ??= new global::BTDB.ODBLayer.DBReaderCtx(Transaction);
                            handler.Skip(ref reader, readerCtx);
                        }
                        else
                        {
                            handler.Skip(ref reader, null);
                        }
                    }
                    if (copyMode)
                    {
                        reader.CopyFromPosToWriter(memoPos, ref writer);
                    }
                }
            }
            base.UpdateByIdFinish(keyBytes, oldValueBytes, writer.GetSpan());
        }
    }
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "_relationInfoResolver")]
    extern static ref global::BTDB.ODBLayer.IRelationInfoResolver RelationInfoResolverAccessor(global::BTDB.ODBLayer.RelationInfo @this);

    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_ClientRelationVersionInfo")]
    extern static global::BTDB.ODBLayer.RelationVersionInfo ClientRelationVersionInfoAccessor(global::BTDB.ODBLayer.RelationInfo @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IPersonTable),
            relationInfo =>
            {
                {
                    var valueFields = ClientRelationVersionInfoAccessor(relationInfo).Fields.Span;
                    var typeConvertorGenerator = RelationInfoResolverAccessor(relationInfo).TypeConvertorGenerator;
                    for (var valueFieldIndex = 0; valueFieldIndex < valueFields.Length; valueFieldIndex++)
                    {
                        var valueField = valueFields[valueFieldIndex];
                        if (valueField.Computed) continue;
                        var paramIndex = -1;
                        if (string.Equals(valueField.Name, "name", StringComparison.OrdinalIgnoreCase))
                        {
                            paramIndex = 0;
                        }
                        if (paramIndex == -1) continue;
                        var handler = valueField.Handler!;
                        switch (paramIndex)
                        {
                            case 0:
                            {
                                var parameterType = typeof(string);
                                var specializedHandler = handler.SpecializeSaveForType(parameterType);
                                if (typeConvertorGenerator.GenerateConversion(parameterType, specializedHandler.HandledType()!) == null)
                                    throw new global::BTDB.KVDBLayer.BTDBException("Method UpdateById matched parameter name has wrong type " + global::BTDB.IL.EmitHelpers.ToSimpleName(parameterType) + " not convertible to " + global::BTDB.IL.EmitHelpers.ToSimpleName(specializedHandler.HandledType()!));
                                break;
                            }
                        }
                    }
                }
                {
                    var valueFields = ClientRelationVersionInfoAccessor(relationInfo).Fields.Span;
                    var typeConvertorGenerator = RelationInfoResolverAccessor(relationInfo).TypeConvertorGenerator;
                    for (var valueFieldIndex = 0; valueFieldIndex < valueFields.Length; valueFieldIndex++)
                    {
                        var valueField = valueFields[valueFieldIndex];
                        if (valueField.Computed) continue;
                        var paramIndex = -1;
                        if (string.Equals(valueField.Name, "secret", StringComparison.OrdinalIgnoreCase))
                        {
                            paramIndex = 0;
                        }
                        if (paramIndex == -1) continue;
                        var handler = valueField.Handler!;
                        switch (paramIndex)
                        {
                            case 0:
                            {
                                var parameterType = typeof(string);
                                var specializedHandler = handler.SpecializeSaveForType(parameterType);
                                if (typeConvertorGenerator.GenerateConversion(parameterType, specializedHandler.HandledType()!) == null)
                                    throw new global::BTDB.KVDBLayer.BTDBException("Method UpdateByIdSecret matched parameter secret has wrong type " + global::BTDB.IL.EmitHelpers.ToSimpleName(parameterType) + " not convertible to " + global::BTDB.IL.EmitHelpers.ToSimpleName(specializedHandler.HandledType()!));
                                break;
                            }
                        }
                    }
                }
                return transaction => new ImplPersonTable(transaction, relationInfo);
            },
            [typeof(global::Person)]);
    }
}
