//HintName: ITestTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
// Name: ITestTable
// Field: Id ulong
//           PrimaryIndex: 1
[CompilerGenerated]
static file class ITestTableRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
    }
}
