//HintName: ILazyUlongListTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: ILazyUlongListTable
// Field: Id ulong
//           PrimaryIndex: 1
// Field: Values global::BTDB.ODBLayer.ILazyUlongList reference

namespace BTDB.GeneratedRelations;
[CompilerGenerated]
file class ILazyUlongListTableRegistration
{
    [Obsolete("BTDB generated relation implementation type is for BTDB internal use only.")]
    public class ImplLazyUlongListTable : global::BTDB.ODBLayer.RelationDBManipulator<global::LazyUlongListRow>, global::ILazyUlongListTable
    {
        public ImplLazyUlongListTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        void global::ILazyUlongListTable.Insert(global::LazyUlongListRow row)
        {
            base.InsertUniqueOrThrow(row);
        }

        [SkipLocalsInit]
        global::LazyUlongListRow global::ILazyUlongListTable.FindById(ulong id)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(id);
            return base.FindByIdOrDefault<global::LazyUlongListRow>(writer.GetSpan(), true, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::ILazyUlongListTable),
            info => { return transaction => new ImplLazyUlongListTable(transaction, info); },
            [typeof(global::LazyUlongListRow)]);
    }
}
