//HintName: Contract.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ContractRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::Contract Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_Id")]
    extern static ulong Getter1(global::IContract @this);
    static void GenGetter1(object @this, ref byte value)
    {
        Unsafe.As<byte, ulong>(ref value) = Getter1(Unsafe.As<global::IContract>(@this));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Id")]
    extern static void Setter1(global::IContract @this, ulong value);
    static void GenSetter1(object @this, ref byte value)
    {
        Setter1(Unsafe.As<global::IContract>(@this), Unsafe.As<byte, ulong>(ref value));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_Name")]
    extern static string Getter2(global::IContract @this);
    static void GenGetter2(object @this, ref byte value)
    {
        Unsafe.As<byte, string>(ref value) = Getter2(Unsafe.As<global::IContract>(@this));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_Name")]
    extern static void Setter2(global::IContract @this, string value);
    static void GenSetter2(object @this, ref byte value)
    {
        Setter2(Unsafe.As<global::IContract>(@this), Unsafe.As<byte, string>(ref value));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Contract), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::Contract();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Contract";
        metadata.Type = typeof(global::Contract);
        metadata.Namespace = "";
        metadata.Implements = [typeof(global::IContract)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::Contract>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                PropRefGetter = &GenGetter1,
                PropRefSetter = &GenSetter1,
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Name",
                Type = typeof(string),
                PropRefGetter = &GenGetter2,
                PropRefSetter = &GenSetter2,
            },
        ];
        metadata.OnSerialize = &OnSerialize;
        static void OnSerialize(object @this)
        {
            Unsafe.As<global::IContract>(@this).Normalize();
        }
        metadata.OnBeforeRemoveFactory = container =>
        {
            global::System.ArgumentNullException.ThrowIfNull(container);
            var f0 = container.CreateFactory(new global::BTDB.IOC.CreateFactoryCtx(), typeof(global::BTDB.IOC.IContainer), "container");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve global::BTDB.IOC.IContainer container parameter of global::Contract.CheckBeforeRemove");
            return (transaction, value) =>
            {
                var val = Unsafe.As<global::Contract>(value);
                var res = false;
                res |= Unsafe.As<global::IContract>(value).CheckBeforeRemove(transaction, Unsafe.As<global::BTDB.IOC.IContainer>(f0(container, null))!);
                return res;
            };
        };
        metadata.PrimaryKeyFields = [0];
        metadata.IndexOfInKeyValue = 1;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
