//HintName: ProductionTrackingDaily.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ProductionTrackingDailyRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::ProductionTrackingDaily Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompanyId>k__BackingField")]
    extern static ref ulong Field1(global::ProductionTrackingDaily @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ProductionDate>k__BackingField")]
    extern static ref global::System.DateTime Field2(global::ProductionTrackingDaily @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::ProductionTrackingDaily), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::ProductionTrackingDaily();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ProductionTrackingDaily";
        metadata.Type = typeof(global::ProductionTrackingDaily);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::ProductionTrackingDaily>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "ProductionDate",
                Type = typeof(global::System.DateTime),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1];
        metadata.IndexOfInKeyValue = 2;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
