//HintName: TestNamespace.IPersonTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
// Name: IPersonTable
// Field: Name string reference

namespace TestNamespace;
[CompilerGenerated]
static file class IPersonTableRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
    }
}
