//HintName: Item.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ItemRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::Item Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    extern static ref ulong Field1(global::Item @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Item), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::Item();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Item";
        metadata.Type = typeof(global::Item);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::Item>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0];
        metadata.IndexOfInKeyValue = 1;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
