//HintName: TestNamespace.ICompanyBackendActionInputIndexerTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: ICompanyBackendActionInputIndexerTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: InputFullName string reference
//           PrimaryIndex: 2
// Field: UniqueKey ulong
//           PrimaryIndex: 3
// Field: ActionId ulong

namespace TestNamespace;
[CompilerGenerated]
file class ICompanyBackendActionInputIndexerTableRegistration
{
    public class ImplCompanyBackendActionInputIndexerTable : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.CompanyBackendActionInputIndexer>, global::TestNamespace.ICompanyBackendActionInputIndexerTable
    {
        public ImplCompanyBackendActionInputIndexerTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        void global::TestNamespace.ICompanyBackendActionInputIndexerTable.Insert(TestNamespace.CompanyBackendActionInputIndexer indexer)
        {
            base.InsertUniqueOrThrow(indexer);
        }

        [SkipLocalsInit]
        void global::TestNamespace.ICompanyBackendActionInputIndexerTable.Update(TestNamespace.CompanyBackendActionInputIndexer inputIndexer)
        {
            base.Update(inputIndexer);
        }

        [SkipLocalsInit]
        global::TestNamespace.CompanyBackendActionInputIndexer? global::TestNamespace.ICompanyBackendActionInputIndexerTable.FindByIdOrDefault(ulong companyId, string inputFullName, ulong uniqueKey)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            writer.WriteStringOrdered(inputFullName);
            writer.WriteVUInt64(uniqueKey);
            return base.FindByIdOrDefault<global::TestNamespace.CompanyBackendActionInputIndexer>(writer.GetSpan(), false, 0);
        }

        [SkipLocalsInit]
        bool global::TestNamespace.ICompanyBackendActionInputIndexerTable.RemoveById(ulong companyId, string inputFullName, ulong uniqueKey)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            writer.WriteStringOrdered(inputFullName);
            writer.WriteVUInt64(uniqueKey);
            var removed = base.RemoveById(writer.GetSpan(), false);
            return removed;
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::TestNamespace.CompanyBackendActionInputIndexer> global::TestNamespace.ICovariantCompanyItemTableBase<global::TestNamespace.CompanyBackendActionInputIndexer>.FindById(ulong companyId)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            return (global::System.Collections.Generic.IEnumerable<global::TestNamespace.CompanyBackendActionInputIndexer>)base.FindByPrimaryKeyPrefix<global::TestNamespace.CompanyBackendActionInputIndexer>(writer.GetSpan(), 0);
        }

        [SkipLocalsInit]
        int global::TestNamespace.ICovariantCompanyItemTableBase<global::TestNamespace.CompanyBackendActionInputIndexer>.RemoveById(ulong companyId)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            return (int)base.RemoveByKeyPrefixWithoutIterate(writer.GetSpan());
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.ICompanyBackendActionInputIndexerTable),
            info => { return transaction => new ImplCompanyBackendActionInputIndexerTable(transaction, info); },
            [typeof(global::TestNamespace.CompanyBackendActionInputIndexer)]);
    }
}
