//HintName: TestNamespace.ItemTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class ItemTableRegistration
{
    static object Creator()
    {
        return RuntimeHelpers.GetUninitializedObject(typeof(global::TestNamespace.ItemTable));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.ItemTable), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::BTDB.ODBLayer.IObjectDBTransaction), "tr");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve BTDB.ODBLayer.IObjectDBTransaction tr parameter of TestNamespace.ItemTable");
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.ItemTable(Unsafe.As<global::BTDB.ODBLayer.IObjectDBTransaction>(f0(container2, ctx2)));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ItemTable";
        metadata.Type = typeof(global::TestNamespace.ItemTable);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.IItemTable), typeof(global::TestNamespace.ICustomRelation), typeof(global::BTDB.ODBLayer.IRelation)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.ItemTable>(metadata);
        metadata.Fields = [
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
