//HintName: IItemTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IItemTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: Queue string reference
//           PrimaryIndex: 2
// Field: ItemId global::System.Guid
//           PrimaryIndex: 3
// Field: Priority int
//           SecondaryIndex LockDeadline: 3 IncludePrimaryKeyOrder 2
// Field: LockDeadline global::System.DateTime
//           SecondaryIndex LockDeadline: 4
[CompilerGenerated]
file class IItemTableRegistration
{
    public class ImplItemTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Item>, global::IItemTable
    {
        public ImplItemTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IItemTable),
            info => { return transaction => new ImplItemTable(transaction, info); },
            [typeof(global::Item)]);
    }
}
