//HintName: Job.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class JobRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::Job Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompanyId>k__BackingField")]
    extern static ref ulong Field1(global::Job @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    extern static ref ulong Field2(global::Job @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastUpdate>k__BackingField")]
    extern static ref global::System.DateTime Field3(global::Job @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Job), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::Job();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Job";
        metadata.Type = typeof(global::Job);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::Job>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "LastUpdate",
                Type = typeof(global::System.DateTime),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1];
        metadata.IndexOfInKeyValue = 2;
        metadata.SecondaryKeys = [("LastUpdate", [0, 2, 1])];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
