//HintName: IProductionTableWithContains.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IProductionTableWithContains
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: ProductionDate global::System.DateTime
//           PrimaryIndex: 2
[CompilerGenerated]
file class IProductionTableWithContainsRegistration
{
    public class ImplProductionTableWithContains : global::BTDB.ODBLayer.RelationDBManipulator<global::ProductionTrackingDaily>, global::IProductionTableWithContains
    {
        public ImplProductionTableWithContains(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        bool global::IProductionTableWithContains.Contains(ulong companyId, System.DateTime productionDate)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            writer.WriteDateTimeForbidUnspecifiedKind(productionDate);
            return base.Contains(writer.GetSpan());
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IProductionTableWithContains),
            info => { return transaction => new ImplProductionTableWithContains(transaction, info); },
            [typeof(global::ProductionTrackingDaily)]);
    }
}
