//HintName: JustAge.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class JustAgeRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::JustAge Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Age>k__BackingField")]
    extern static ref int Field1(global::JustAge @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::JustAge), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::JustAge();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "JustAge";
        metadata.Type = typeof(global::JustAge);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::JustAge>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Age",
                Type = typeof(int),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
