//HintName: ISimpleRelation.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: ISimpleRelation
// Field: Id ulong
//           PrimaryIndex: 1
// Field: Name string reference
//           SecondaryIndex Name: 0
[CompilerGenerated]
file class ISimpleRelationRegistration
{
    public class ImplSimpleRelation : global::BTDB.ODBLayer.RelationDBManipulator<global::SimpleObject>, global::ISimpleRelation
    {
        public ImplSimpleRelation(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::SimpleObject> global::ISimpleRelation.ListByName(string name, BTDB.ODBLayer.AdvancedEnumeratorParam<ulong> param)
        {
            var remappedSecondaryKeyIndex = RemapPrimeSK(0u);
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationSKPrefix(ref writer, remappedSecondaryKeyIndex);
            writer.WriteStringOrdered(name);
            var prefixLen = (int)writer.GetCurrentPosition();
            if (param.StartProposition != global::BTDB.ODBLayer.KeyProposition.Ignored)
            {
                writer.WriteVUInt64(param.Start);
            }
            var startKeyBytes = writer.GetScopedSpanAndReset();
            WriteRelationSKPrefix(ref writer, remappedSecondaryKeyIndex);
            writer.WriteStringOrdered(name);
            if (param.EndProposition != global::BTDB.ODBLayer.KeyProposition.Ignored)
            {
                writer.WriteVUInt64(param.End);
            }
            var endKeyBytes = writer.GetSpan();
            return new global::BTDB.ODBLayer.RelationAdvancedSecondaryKeyEnumerator<global::SimpleObject>(this, param.Order, param.StartProposition, prefixLen, startKeyBytes, param.EndProposition, endKeyBytes, remappedSecondaryKeyIndex, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::ISimpleRelation),
            info => { return transaction => new ImplSimpleRelation(transaction, info); },
            [typeof(global::SimpleObject)]);
    }
}
