//HintName: ThingWithSK.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ThingWithSKRegistration
{
    static object Creator()
    {
        return RuntimeHelpers.GetUninitializedObject(typeof(global::ThingWithSK));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Tenant>k__BackingField")]
    extern static ref ulong Field1(global::ThingWithSK @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
    extern static ref string Field2(global::ThingWithSK @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Age>k__BackingField")]
    extern static ref uint Field3(global::ThingWithSK @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::ThingWithSK), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(ulong), "tenant");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve ulong tenant parameter of ThingWithSK");
            var f1 = container.CreateFactory(ctx, typeof(string), "name");
            if (f1 == null) throw new global::System.ArgumentException("Cannot resolve string name parameter of ThingWithSK");
            var f2 = container.CreateFactory(ctx, typeof(uint), "age");
            if (f2 == null) throw new global::System.ArgumentException("Cannot resolve uint age parameter of ThingWithSK");
            return (container2, ctx2) =>
            {
                var res = new global::ThingWithSK((ulong)(f0(container2, ctx2)), Unsafe.As<string>(f1(container2, ctx2)), (uint)(f2(container2, ctx2)));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ThingWithSK";
        metadata.Type = typeof(global::ThingWithSK);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::ThingWithSK>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Tenant",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Name",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Age",
                Type = typeof(uint),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1];
        metadata.IndexOfInKeyValue = 2;
        metadata.SecondaryKeys = [("Name", [1, 2, 0])];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
