//HintName: TestNamespace.FakeTeamVisibility.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class FakeTeamVisibilityRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.FakeTeamVisibility Creator();
    public static class GetterAdapter1<TItemId>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_CompanyId")]
        extern public static ulong Getter(global::Sample3rdPartyLib.ExternalTeamVisibility<TItemId> @this);
    }
    static void GenGetter1(object @this, ref byte value)
    {
        Unsafe.As<byte, ulong>(ref value) = GetterAdapter1<ulong>.Getter(Unsafe.As<global::Sample3rdPartyLib.ExternalTeamVisibility<ulong>>(@this));
    }
    public static class SetterAdapter1<TItemId>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_CompanyId")]
        extern public static void Setter(global::Sample3rdPartyLib.ExternalTeamVisibility<TItemId> @this, ulong value);
    }
    static void GenSetter1(object @this, ref byte value)
    {
        SetterAdapter1<ulong>.Setter(Unsafe.As<global::Sample3rdPartyLib.ExternalTeamVisibility<ulong>>(@this), Unsafe.As<byte, ulong>(ref value));
    }
    public static class GetterAdapter2<TItemId>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_TeamId")]
        extern public static ulong Getter(global::Sample3rdPartyLib.ExternalTeamVisibility<TItemId> @this);
    }
    static void GenGetter2(object @this, ref byte value)
    {
        Unsafe.As<byte, ulong>(ref value) = GetterAdapter2<ulong>.Getter(Unsafe.As<global::Sample3rdPartyLib.ExternalTeamVisibility<ulong>>(@this));
    }
    public static class SetterAdapter2<TItemId>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_TeamId")]
        extern public static void Setter(global::Sample3rdPartyLib.ExternalTeamVisibility<TItemId> @this, ulong value);
    }
    static void GenSetter2(object @this, ref byte value)
    {
        SetterAdapter2<ulong>.Setter(Unsafe.As<global::Sample3rdPartyLib.ExternalTeamVisibility<ulong>>(@this), Unsafe.As<byte, ulong>(ref value));
    }
    public static class GetterAdapter3<TItemId>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "get_ItemId")]
        extern public static TItemId Getter(global::Sample3rdPartyLib.ExternalTeamVisibility<TItemId> @this);
    }
    static void GenGetter3(object @this, ref byte value)
    {
        Unsafe.As<byte, ulong>(ref value) = GetterAdapter3<ulong>.Getter(Unsafe.As<global::Sample3rdPartyLib.ExternalTeamVisibility<ulong>>(@this));
    }
    public static class SetterAdapter3<TItemId>
    {
        [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "set_ItemId")]
        extern public static void Setter(global::Sample3rdPartyLib.ExternalTeamVisibility<TItemId> @this, TItemId value);
    }
    static void GenSetter3(object @this, ref byte value)
    {
        SetterAdapter3<ulong>.Setter(Unsafe.As<global::Sample3rdPartyLib.ExternalTeamVisibility<ulong>>(@this), Unsafe.As<byte, ulong>(ref value));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.FakeTeamVisibility), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.FakeTeamVisibility();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "FakeTeamVisibility";
        metadata.Type = typeof(global::TestNamespace.FakeTeamVisibility);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.FakeTeamVisibility>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                PropRefGetter = &GenGetter1,
                PropRefSetter = &GenSetter1,
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "TeamId",
                Type = typeof(ulong),
                PropRefGetter = &GenGetter2,
                PropRefSetter = &GenSetter2,
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "ItemId",
                Type = typeof(ulong),
                PropRefGetter = &GenGetter3,
                PropRefSetter = &GenSetter3,
            },
        ];
        metadata.PrimaryKeyFields = [0, 1, 2];
        metadata.IndexOfInKeyValue = 3;
        metadata.SecondaryKeys = [("Item", [0, 2, 1])];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
