//HintName: DeliveryRuleV1.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class DeliveryRuleV1Registration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::DeliveryRuleV1 Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Activities>k__BackingField")]
    extern static ref global::System.Collections.Generic.IList<global::Activity> Field1(global::DeliveryRuleV1 @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    extern static ref ulong Field2(global::DeliveryRuleV1 @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
    extern static ref int Field3(global::DeliveryRuleV1 @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::DeliveryRuleV1), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::DeliveryRuleV1();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "DeliveryRuleV1";
        metadata.Type = typeof(global::DeliveryRuleV1);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::DeliveryRuleV1>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Activities",
                Type = typeof(global::System.Collections.Generic.IList<global::Activity>),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Status",
                Type = typeof(int),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
