//HintName: IUserNoticeTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IUserNoticeTable
// Field: UserId ulong
//           PrimaryIndex: 1
// Field: NoticeId ulong
//           PrimaryIndex: 2
//           SecondaryIndex NoticeId: 0
[CompilerGenerated]
file class IUserNoticeTableRegistration
{
    public class ImplUserNoticeTable : global::BTDB.ODBLayer.RelationDBManipulator<global::UserNotice>, global::IUserNoticeTable
    {
        public ImplUserNoticeTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        void global::IUserNoticeTable.Insert(UserNotice un)
        {
            base.InsertUniqueOrThrow(un);
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::UserNotice> global::IUserNoticeTable.ListByNoticeId(BTDB.ODBLayer.AdvancedEnumeratorParam<ulong> noticeId)
        {
            var remappedSecondaryKeyIndex = RemapPrimeSK(0u);
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationSKPrefix(ref writer, remappedSecondaryKeyIndex);
            var prefixLen = (int)writer.GetCurrentPosition();
            if (noticeId.StartProposition != global::BTDB.ODBLayer.KeyProposition.Ignored)
            {
                writer.WriteVUInt64(noticeId.Start);
            }
            var startKeyBytes = writer.GetScopedSpanAndReset();
            WriteRelationSKPrefix(ref writer, remappedSecondaryKeyIndex);
            if (noticeId.EndProposition != global::BTDB.ODBLayer.KeyProposition.Ignored)
            {
                writer.WriteVUInt64(noticeId.End);
            }
            var endKeyBytes = writer.GetSpan();
            return new global::BTDB.ODBLayer.RelationAdvancedSecondaryKeyEnumerator<global::UserNotice>(this, noticeId.Order, noticeId.StartProposition, prefixLen, startKeyBytes, noticeId.EndProposition, endKeyBytes, remappedSecondaryKeyIndex, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IUserNoticeTable),
            info => { return transaction => new ImplUserNoticeTable(transaction, info); },
            [typeof(global::UserNotice)]);
    }
}
