//HintName: IJobTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IJobTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: Id ulong
//           PrimaryIndex: 2
// Field: LastUpdate global::System.DateTime
//           SecondaryIndex LastUpdate: 0 IncludePrimaryKeyOrder 1
[CompilerGenerated]
file class IJobTableRegistration
{
    public class ImplJobTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Job>, global::IJobTable
    {
        public ImplJobTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::Job? global::IJobTable.FirstByLastUpdateOrDefault(BTDB.ODBLayer.Constraint<ulong> companyId, BTDB.ODBLayer.IOrderer[]? orderer)
        {
            var c_c = new ConstraintInfo[1];
            c_c[0].Constraint = companyId;
            return FirstBySecondaryKey<global::Job>(0, c_c, 0u, orderer, true);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IJobTable),
            info => { return transaction => new ImplJobTable(transaction, info); },
            [typeof(global::Job)]);
    }
}
