//HintName: UserNotice.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class UserNoticeRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::UserNotice Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
    extern static ref ulong Field1(global::UserNotice @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NoticeId>k__BackingField")]
    extern static ref ulong Field2(global::UserNotice @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::UserNotice), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::UserNotice();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "UserNotice";
        metadata.Type = typeof(global::UserNotice);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::UserNotice>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "UserId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "NoticeId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1];
        metadata.IndexOfInKeyValue = 2;
        metadata.SecondaryKeys = [("NoticeId", [1, 0])];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
