//HintName: IPersonTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IPersonTable
// Field: Id ulong
//           PrimaryIndex: 0
// Field: Name string reference

namespace BTDB.GeneratedRelations;
[CompilerGenerated]
file class IPersonTableRegistration
{
    [Obsolete("BTDB generated relation implementation type is for BTDB internal use only.")]
    public class ImplPersonTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Person>, global::IPersonTable
    {
        public ImplPersonTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        void global::IPersonTable.Update(global::Person person)
        {
            base.Update(person);
        }

        [SkipLocalsInit]
        void global::IPersonTable.ShallowUpdate(global::Person person)
        {
            base.ShallowUpdate(person);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IPersonTable),
            info => { return transaction => new ImplPersonTable(transaction, info); },
            [typeof(global::Person)]);
    }
}
