//HintName: IDataSamePrefixTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IDataSamePrefixTable
// Field: A int
//           PrimaryIndex: 1
//           SecondaryIndex S: 1
// Field: B int
//           PrimaryIndex: 2
// Field: C int
//           PrimaryIndex: 3
//           SecondaryIndex S: 2
[CompilerGenerated]
file class IDataSamePrefixTableRegistration
{
    public class ImplDataSamePrefixTable : global::BTDB.ODBLayer.RelationDBManipulator<global::DataSamePrefix>, global::IDataSamePrefixTable
    {
        public ImplDataSamePrefixTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        int global::IDataSamePrefixTable.RemoveById(int a)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVInt64(a);
            return (int)base.RemoveByKeyPrefixWithoutIterate(writer.GetSpan());
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IDataSamePrefixTable),
            info => { return transaction => new ImplDataSamePrefixTable(transaction, info); },
            [typeof(global::DataSamePrefix)]);
    }
}
