//HintName: Microsoft.Extensions.Primitives.StringValues.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace Microsoft.Extensions.Primitives;

[CompilerGenerated]
static file class StringValuesRegistration
{
    static object Creator()
    {
        return RuntimeHelpers.GetUninitializedObject(typeof(global::Microsoft.Extensions.Primitives.StringValues));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "System.Collections.Generic.IList<System.String>.get_Item")]
    extern static string Getter1(global::Microsoft.Extensions.Primitives.StringValues @this);
    static void GenGetter1(object @this, ref byte value)
    {
        Unsafe.As<byte, string>(ref value) = Getter1(Unsafe.As<global::Microsoft.Extensions.Primitives.StringValues>(@this));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "System.Collections.Generic.IList<System.String>.set_Item")]
    extern static void Setter1(global::Microsoft.Extensions.Primitives.StringValues @this, string value);
    static void GenSetter1(object @this, ref byte value)
    {
        Setter1(Unsafe.As<global::Microsoft.Extensions.Primitives.StringValues>(@this), Unsafe.As<byte, string>(ref value));
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Microsoft.Extensions.Primitives.StringValues), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(string), "value");
            return (container2, ctx2) =>
            {
                var res = new global::Microsoft.Extensions.Primitives.StringValues(f0 != null ? Unsafe.As<string>(f0(container2, ctx2)) : default(string));
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "StringValues";
        metadata.Type = typeof(global::Microsoft.Extensions.Primitives.StringValues);
        metadata.Namespace = "Microsoft.Extensions.Primitives";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::Microsoft.Extensions.Primitives.StringValues>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "System.Collections.Generic.IList<System.String>.Item",
                Type = typeof(string),
                PropRefGetter = &GenGetter1,
                PropRefSetter = &GenSetter1,
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
