//HintName: System.Net.IPAddress.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace System.Net;

[CompilerGenerated]
static file class IPAddressRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::System.Net.IPAddress), (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(byte[]), "address");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve byte[] address parameter of System.Net.IPAddress");
            var f1 = container.CreateFactory(ctx, typeof(long), "scopeid");
            if (f1 == null) throw new global::System.ArgumentException("Cannot resolve long scopeid parameter of System.Net.IPAddress");
            return (container2, ctx2) =>
            {
                var res = new global::System.Net.IPAddress(Unsafe.As<byte[]>(f0(container2, ctx2)), (long)(f1(container2, ctx2)));
                return res;
            };
        });
    }
}
