//HintName: IItemTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IItemTable
// Field: Id ulong
//           PrimaryIndex: 0
[CompilerGenerated]
file class IItemTableRegistration
{
    public class ImplItemTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Item>, global::IItemTable
    {
        public ImplItemTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        void global::IItemTable.Update(Item item)
        {
            base.Update(item);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IItemTable),
            info => { return transaction => new ImplItemTable(transaction, info); },
            [typeof(global::Item)]);
    }
}
