//HintName: CompanyUserRole.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class CompanyUserRoleRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::CompanyUserRole Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompanyId>k__BackingField")]
    extern static ref ulong Field1(global::CompanyUserRole @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
    extern static ref ulong Field2(global::CompanyUserRole @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RoleId>k__BackingField")]
    extern static ref ulong Field3(global::CompanyUserRole @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::CompanyUserRole), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::CompanyUserRole();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "CompanyUserRole";
        metadata.Type = typeof(global::CompanyUserRole);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::CompanyUserRole>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "UserId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "RoleId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1, 2];
        metadata.IndexOfInKeyValue = 3;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
