//HintName: IItemTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IItemTable
// Field: Id ulong
//           PrimaryIndex: 1
[CompilerGenerated]
file class IItemTableRegistration
{
    public class ImplItemTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Item>, global::IItemTable
    {
        public ImplItemTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        ulong global::IItemTable.GatherById(System.Collections.Generic.List<Item> items, long skip, long take, BTDB.ODBLayer.Constraint<ulong> id)
        {
            var c_c = new ConstraintInfo[1];
            c_c[0].Constraint = id;
            return GatherByPrimaryKey(0, c_c, items, skip, take, null);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IItemTable),
            info => { return transaction => new ImplItemTable(transaction, info); },
            [typeof(global::Item)]);
    }
}
