//HintName: IPersonTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IPersonTable
// Field: Id ulong
//           PrimaryIndex: 1
// Field: Name string reference
[CompilerGenerated]
file class IPersonTableRegistration
{
    public class ImplPersonTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Person>, global::IPersonTable
    {
        public ImplPersonTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::Person> global::IPersonTable.ScanById(BTDB.ODBLayer.Constraint<ulong> id)
        {
            var c_c = new ConstraintInfo[1];
            c_c[0].Constraint = id;
            return ScanByPrimaryKeyPrefix<global::Person>(0, c_c);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IPersonTable),
            info => { return transaction => new ImplPersonTable(transaction, info); },
            [typeof(global::Person)]);
    }
}
