//HintName: TestNamespace.StateItemIndexes.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class StateItemIndexesRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.StateItemIndexes Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompanyId>k__BackingField")]
    extern static ref ulong Field1(global::TestNamespace.StateItemIndexes @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StateGroupId>k__BackingField")]
    extern static ref uint Field2(global::TestNamespace.StateItemIndexes @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ItemId>k__BackingField")]
    extern static ref ulong Field3(global::TestNamespace.StateItemIndexes @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Indexes>k__BackingField")]
    extern static ref global::System.Collections.Generic.IList<ulong> Field4(global::TestNamespace.StateItemIndexes @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.StateItemIndexes), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.StateItemIndexes();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "StateItemIndexes";
        metadata.Type = typeof(global::TestNamespace.StateItemIndexes);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.StateItemIndexes>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "StateGroupId",
                Type = typeof(uint),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "ItemId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Indexes",
                Type = typeof(global::System.Collections.Generic.IList<ulong>),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field4(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1, 2];
        metadata.IndexOfInKeyValue = 3;
        metadata.SecondaryKeys = [("Indexes", [0, 1, 3, 2])];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
