//HintName: IPersonTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IPersonTable
// Field: TenantId ulong
//           PrimaryIndex: 1
// Field: Id ulong
//           PrimaryIndex: 2
// Field: Name string reference
// Field: Secret global::BTDB.Encrypted.EncryptedString
[CompilerGenerated]
file class IPersonTableRegistration
{
    public class ImplPersonTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Person>, global::IPersonTable
    {
        public ImplPersonTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        bool global::IPersonTable.UpdateById(ulong tenantId, ulong id)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            var lenOfPkWoInKeyValues = 0;
            writer.WriteVUInt64(tenantId);
            writer.WriteVUInt64(id);
            var keyBytes = writer.GetScopedSpanAndReset();
            var updated = base.UpdateByIdInKeyValues(keyBytes, lenOfPkWoInKeyValues, false);
            return updated;
        }

        [SkipLocalsInit]
        bool global::IPersonTable.UpdateById(ulong tenantId, ulong id, string name)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            var lenOfPkWoInKeyValues = 0;
            writer.WriteVUInt64(tenantId);
            writer.WriteVUInt64(id);
            var keyBytes = writer.GetScopedSpanAndReset();
            var oldValueBytes = default(global::System.ReadOnlySpan<byte>);
            var updated = base.UpdateByIdStart(keyBytes, ref writer, ref oldValueBytes, lenOfPkWoInKeyValues, false);
            if (!updated) return false;
            global::BTDB.ODBLayer.DBReaderCtx? ctx_reader = null;
            if (RelationInfo.ClientVersionNeedsCtx)
            {
                ctx_reader = new global::BTDB.ODBLayer.DBReaderCtx(Transaction);
            }
            unsafe
            {
                fixed (byte* _ = oldValueBytes)
                {
                    var reader = global::BTDB.StreamLayer.MemReader.CreateFromPinnedSpan(oldValueBytes);
                    uint memoPos = 0;
                    reader.SkipVUInt64();
                    reader.SkipString();
                    writer.WriteString(name);
                    memoPos = (uint)reader.GetCurrentPositionWithoutController();
                    RelationInfo.ClientVersionValueHandlers[1].Skip(ref reader, ctx_reader);
                    reader.CopyFromPosToWriter(memoPos, ref writer);
                }
            }
            base.UpdateByIdFinish(keyBytes, oldValueBytes, writer.GetSpan());
            return true;
        }

        [SkipLocalsInit]
        void global::IPersonTable.UpdateByIdSecret(ulong tenantId, ulong id, BTDB.Encrypted.EncryptedString secret)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            var lenOfPkWoInKeyValues = 0;
            writer.WriteVUInt64(tenantId);
            writer.WriteVUInt64(id);
            var keyBytes = writer.GetScopedSpanAndReset();
            var oldValueBytes = default(global::System.ReadOnlySpan<byte>);
            _ = base.UpdateByIdStart(keyBytes, ref writer, ref oldValueBytes, lenOfPkWoInKeyValues, true);
            global::BTDB.ODBLayer.DBReaderCtx? ctx_reader = null;
            var ctx_ctx = new global::BTDB.ODBLayer.DBWriterCtx(Transaction);
            if (RelationInfo.ClientVersionNeedsCtx)
            {
                ctx_reader = new global::BTDB.ODBLayer.DBReaderCtx(Transaction);
            }
            unsafe
            {
                fixed (byte* _ = oldValueBytes)
                {
                    var reader = global::BTDB.StreamLayer.MemReader.CreateFromPinnedSpan(oldValueBytes);
                    uint memoPos = 0;
                    reader.SkipVUInt64();
                    memoPos = (uint)reader.GetCurrentPositionWithoutController();
                    reader.SkipString();
                    reader.CopyFromPosToWriter(memoPos, ref writer);
                    RelationInfo.ClientVersionValueHandlers[1].Skip(ref reader, ctx_reader);
                    ctx_ctx.WriteEncryptedString(ref writer, secret);
                }
            }
            base.UpdateByIdFinish(keyBytes, oldValueBytes, writer.GetSpan());
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IPersonTable),
            info => { return transaction => new ImplPersonTable(transaction, info); },
            [typeof(global::Person)]);
    }
}
