//HintName: TestNamespace.CompanyBackendActionInputIndexer.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

[CompilerGenerated]
static file class CompanyBackendActionInputIndexerRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::TestNamespace.CompanyBackendActionInputIndexer Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompanyId>k__BackingField")]
    extern static ref ulong Field1(global::TestNamespace.CompanyBackendActionInputIndexer @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<InputFullName>k__BackingField")]
    extern static ref string Field2(global::TestNamespace.CompanyBackendActionInputIndexer @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UniqueKey>k__BackingField")]
    extern static ref ulong Field3(global::TestNamespace.CompanyBackendActionInputIndexer @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ActionId>k__BackingField")]
    extern static ref ulong Field4(global::TestNamespace.CompanyBackendActionInputIndexer @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.CompanyBackendActionInputIndexer), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::TestNamespace.CompanyBackendActionInputIndexer();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "CompanyBackendActionInputIndexer";
        metadata.Type = typeof(global::TestNamespace.CompanyBackendActionInputIndexer);
        metadata.Namespace = "TestNamespace";
        metadata.Implements = [typeof(global::TestNamespace.ICompanyRecord)];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::TestNamespace.CompanyBackendActionInputIndexer>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "InputFullName",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "UniqueKey",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "ActionId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field4(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1, 2];
        metadata.IndexOfInKeyValue = 3;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
