//HintName: IProductTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IProductTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: ProductId ulong
//           PrimaryIndex: 2
// Field: Name string reference
[CompilerGenerated]
file class IProductTableRegistration
{
    public class ImplProductTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Product>, global::IProductTable
    {
        public ImplProductTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        bool global::IProductTable.AnyById(ulong companyId, BTDB.ODBLayer.AdvancedEnumeratorParam<ulong> productIdParam)
        {
            throw new NotImplementedException();
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IProductTable),
            info => { return transaction => new ImplProductTable(transaction, info); },
            [typeof(global::Product)]);
    }
}
