//HintName: IContentVersionTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IContentVersionTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: ContentId ulong
//           PrimaryIndex: 2
// Field: Version uint
//           PrimaryIndex: 3
//           SecondaryIndex State: 4
// Field: State global::ContentVersionState
//           SecondaryIndex State: 3 IncludePrimaryKeyOrder 2
[CompilerGenerated]
file class IContentVersionTableRegistration
{
    public class ImplContentVersionTable : global::BTDB.ODBLayer.RelationDBManipulator<global::ContentVersion>, global::IContentVersionTable
    {
        public ImplContentVersionTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::ContentVersion> global::IContentVersionTable.ListByState(ulong companyId, ulong contentId, ContentVersionState state, BTDB.ODBLayer.AdvancedEnumeratorParam<uint> param)
        {
            var remappedSecondaryKeyIndex = RemapPrimeSK(0u);
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationSKPrefix(ref writer, remappedSecondaryKeyIndex);
            writer.WriteVUInt64(companyId);
            writer.WriteVUInt64(contentId);
            writer.WriteVInt64((long)state);
            var prefixLen = (int)writer.GetCurrentPosition();
            if (param.StartProposition != global::BTDB.ODBLayer.KeyProposition.Ignored)
            {
                writer.WriteVUInt64(param.Start);
            }
            var startKeyBytes = writer.GetScopedSpanAndReset();
            WriteRelationSKPrefix(ref writer, remappedSecondaryKeyIndex);
            writer.WriteVUInt64(companyId);
            writer.WriteVUInt64(contentId);
            writer.WriteVInt64((long)state);
            if (param.EndProposition != global::BTDB.ODBLayer.KeyProposition.Ignored)
            {
                writer.WriteVUInt64(param.End);
            }
            var endKeyBytes = writer.GetSpan();
            return new global::BTDB.ODBLayer.RelationAdvancedSecondaryKeyEnumerator<global::ContentVersion>(this, param.Order, param.StartProposition, prefixLen, startKeyBytes, param.EndProposition, endKeyBytes, remappedSecondaryKeyIndex, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IContentVersionTable),
            info => { return transaction => new ImplContentVersionTable(transaction, info); },
            [typeof(global::ContentVersion)]);
    }
}
