//HintName: TestNamespace.IPersonTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IPersonTable
// Field: ParentId int
//           PrimaryIndex: 1
// Field: PersonId int
//           PrimaryIndex: 2
// Field: Name string reference

namespace TestNamespace;
[CompilerGenerated]
file class IPersonTableRegistration
{
    public class ImplPersonTable : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.Person>, global::TestNamespace.IPersonTable
    {
        public ImplPersonTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.IPersonTable),
            info => { return transaction => new ImplPersonTable(transaction, info); },
            [typeof(global::TestNamespace.Person)]);
    }
}
