//HintName: IUserNoticeTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
// Name: IUserNoticeTable
// Field: UserId ulong
//           PrimaryIndex: 1
// Field: NoticeId ulong
//           PrimaryIndex: 2
//           SecondaryIndex NoticeId: 0
[CompilerGenerated]
static file class IUserNoticeTableRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
    }
}
