//HintName: IEntityTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IEntityTable
// Field: TenantId ulong
//           PrimaryIndex: 1
// Field: Name string reference
[CompilerGenerated]
file class IEntityTableRegistration
{
    public class ImplEntityTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Entity>, global::IEntityTable
    {
        public ImplEntityTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::Entity global::IEntityTable.FindById(ulong tenantId)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(tenantId);
            return base.FindByIdOrDefault<global::Entity>(writer.GetSpan(), true, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IEntityTable),
            info => { return transaction => new ImplEntityTable(transaction, info); },
            [typeof(global::Entity)]);
    }
}
