//HintName: TestNamespace.IPersonTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IPersonTable
// Field: Name string reference

namespace BTDB.GeneratedRelations;
[CompilerGenerated]
file class IPersonTableRegistration
{
    [Obsolete("BTDB generated relation implementation type is for BTDB internal use only.")]
    public class ImplPersonTable : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.Person>, global::TestNamespace.IPersonTable
    {
        public ImplPersonTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.IPersonTable),
            info => { return transaction => new ImplPersonTable(transaction, info); },
            [typeof(global::TestNamespace.Person)]);
    }
}
