//HintName: BTDB.Encrypted.EncryptedString.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

namespace BTDB.Encrypted;

[CompilerGenerated]
static file class EncryptedStringRegistration
{
    static object Creator()
    {
        return RuntimeHelpers.GetUninitializedObject(typeof(global::BTDB.Encrypted.EncryptedString));
    }
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "Secret")]
    extern static ref string Field1(global::BTDB.Encrypted.EncryptedString @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {

        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "EncryptedString";
        metadata.Type = typeof(global::BTDB.Encrypted.EncryptedString);
        metadata.Namespace = "BTDB.Encrypted";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::BTDB.Encrypted.EncryptedString>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Secret",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
        ];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);    }
}
