//HintName: IContainsKeyTypesTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IContainsKeyTypesTable
// Field: Name string reference
//           PrimaryIndex: 1
// Field: Duration global::System.TimeSpan
//           PrimaryIndex: 2
// Field: Address global::System.Net.IPAddress reference
//           PrimaryIndex: 3
// Field: ApiVersion global::System.Version reference
//           PrimaryIndex: 4
// Field: Tags global::Microsoft.Extensions.Primitives.StringValues reference
//           PrimaryIndex: 5
// Field: Names global::System.Collections.Generic.List<string> reference
//           PrimaryIndex: 6
// Field: Counters global::System.Collections.Generic.List<ulong> reference
//           PrimaryIndex: 7
[CompilerGenerated]
file class IContainsKeyTypesTableRegistration
{
    public class ImplContainsKeyTypesTable : global::BTDB.ODBLayer.RelationDBManipulator<global::ContainsKeyTypes>, global::IContainsKeyTypesTable
    {
        public ImplContainsKeyTypesTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        bool global::IContainsKeyTypesTable.Contains(string name, System.TimeSpan duration, System.Net.IPAddress address, System.Version apiVersion, Microsoft.Extensions.Primitives.StringValues tags, System.Collections.Generic.List<string> names, System.Collections.Generic.List<ulong> counters)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteStringOrdered(name);
            writer.WriteTimeSpan(duration);
            writer.WriteIPAddress(address);
            writer.WriteVersion(apiVersion);
            writer.WriteStringValues(tags);
            if (names == null) writer.WriteVUInt32(0); else { writer.WriteVUInt32((uint)names.Count); foreach (var item in names) writer.WriteString(item); }
            if (counters == null) writer.WriteVUInt32(0); else { writer.WriteVUInt32((uint)counters.Count); foreach (var item in counters) writer.WriteVUInt64(item); }
            return base.Contains(writer.GetSpan());
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IContainsKeyTypesTable),
            info => { return transaction => new ImplContainsKeyTypesTable(transaction, info); },
            [typeof(global::ContainsKeyTypes)]);
    }
}
