//HintName: SimpleObject.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class SimpleObjectRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::SimpleObject Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    extern static ref ulong Field1(global::SimpleObject @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
    extern static ref string Field2(global::SimpleObject @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::SimpleObject), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::SimpleObject();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "SimpleObject";
        metadata.Type = typeof(global::SimpleObject);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::SimpleObject>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Name",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0];
        metadata.IndexOfInKeyValue = 1;
        metadata.SecondaryKeys = [("Name", [1, 0])];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
