//HintName: DataSamePrefix.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class DataSamePrefixRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::DataSamePrefix Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<A>k__BackingField")]
    extern static ref int Field1(global::DataSamePrefix @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<B>k__BackingField")]
    extern static ref int Field2(global::DataSamePrefix @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<C>k__BackingField")]
    extern static ref int Field3(global::DataSamePrefix @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::DataSamePrefix), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::DataSamePrefix();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "DataSamePrefix";
        metadata.Type = typeof(global::DataSamePrefix);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::DataSamePrefix>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "A",
                Type = typeof(int),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "B",
                Type = typeof(int),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "C",
                Type = typeof(int),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1, 2];
        metadata.IndexOfInKeyValue = 3;
        metadata.SecondaryKeys = [("S", [0, 2, 1])];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
