//HintName: BitmapRow.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class BitmapRowRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::BitmapRow Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
    extern static ref ulong Field1(global::BitmapRow @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bits>k__BackingField")]
    extern static ref global::BTDB.ODBLayer.IRoaringBitmap Field2(global::BitmapRow @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::BitmapRow), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::BitmapRow();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "BitmapRow";
        metadata.Type = typeof(global::BitmapRow);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::BitmapRow>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Id",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Bits",
                Type = typeof(global::BTDB.ODBLayer.IRoaringBitmap),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0];
        metadata.IndexOfInKeyValue = 1;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
