//HintName: ICompanyUserRoleTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: ICompanyUserRoleTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: UserId ulong
//           PrimaryIndex: 2
// Field: RoleId ulong
//           PrimaryIndex: 3

namespace BTDB.GeneratedRelations;
[CompilerGenerated]
file class ICompanyUserRoleTableRegistration
{
    [Obsolete("BTDB generated relation implementation type is for BTDB internal use only.")]
    public class ImplCompanyUserRoleTable : global::BTDB.ODBLayer.RelationDBManipulator<global::CompanyUserRole>, global::ICompanyUserRoleTable
    {
        public ImplCompanyUserRoleTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        void global::ICompanyUserRoleTable.IterateById(ulong companyId, global::System.Action<global::CompanyUserRoleIteration> callback, global::CompanyUserRoleIteration value)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            base.IterateByPrimaryKeyPrefix<global::CompanyUserRoleIteration>(writer.GetSpan(), 1, 1, callback, value);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::ICompanyUserRoleTable),
            info => { return transaction => new ImplCompanyUserRoleTable(transaction, info); },
            [typeof(global::CompanyUserRole), typeof(global::CompanyUserRoleIteration)]);
    }
}
