//HintName: Gmc.Cloud.Processing.IJobTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IJobTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: Status global::Infrastructure.Impress.Status
//           PrimaryIndex: 2

namespace Gmc.Cloud.Processing;
[CompilerGenerated]
file class IJobTableRegistration
{
    public class ImplJobTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Gmc.Cloud.Processing.Job>, global::Gmc.Cloud.Processing.IJobTable
    {
        public ImplJobTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::Gmc.Cloud.Processing.Job? global::Gmc.Cloud.Processing.IJobTable.FindByIdOrDefault(ulong companyId, global::Infrastructure.Impress.Status status)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            writer.WriteVInt64((long)status);
            return base.FindByIdOrDefault<global::Gmc.Cloud.Processing.Job>(writer.GetSpan(), false, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::Gmc.Cloud.Processing.IJobTable),
            info => { return transaction => new ImplJobTable(transaction, info); },
            [typeof(global::Gmc.Cloud.Processing.Job)]);
    }
}
