//HintName: IPeripheryMigrationInfoTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
// Name: IPeripheryMigrationInfoTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
[CompilerGenerated]
static file class IPeripheryMigrationInfoTableRegistration
{
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
    }
}
