//HintName: IPersonTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IPersonTable
// Field: Id uint
//           PrimaryIndex: 1
[CompilerGenerated]
file class IPersonTableRegistration
{
    public class ImplPersonTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Person>, global::IPersonTable
    {
        public ImplPersonTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        void global::IPersonTable.Insert(Person person)
        {
            base.InsertUniqueOrThrow(person);
        }

        [SkipLocalsInit]
        global::Person global::IPersonTable.FindByIdOrDefault(ulong id)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(id);
            return base.FindByIdOrDefault<global::Person>(writer.GetSpan(), false, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IPersonTable),
            info => { return transaction => new ImplPersonTable(transaction, info); },
            [typeof(global::Person)]);
    }
}
