//HintName: ContentVersion.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class ContentVersionRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::ContentVersion Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompanyId>k__BackingField")]
    extern static ref ulong Field1(global::ContentVersion @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ContentId>k__BackingField")]
    extern static ref ulong Field2(global::ContentVersion @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Version>k__BackingField")]
    extern static ref uint Field3(global::ContentVersion @this);
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<State>k__BackingField")]
    extern static ref global::ContentVersionState Field4(global::ContentVersion @this);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::ContentVersion), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::ContentVersion();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "ContentVersion";
        metadata.Type = typeof(global::ContentVersion);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::ContentVersion>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "CompanyId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "ContentId",
                Type = typeof(ulong),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field2(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Version",
                Type = typeof(uint),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field3(dummy)),
            },
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "State",
                Type = typeof(global::ContentVersionState),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field4(dummy)),
            },
        ];
        metadata.PrimaryKeyFields = [0, 1, 2];
        metadata.IndexOfInKeyValue = 3;
        metadata.SecondaryKeys = [("State", [0, 1, 3, 2])];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
