//HintName: IEmailTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IEmailTable
// Field: Id ulong
//           PrimaryIndex: 1
// Field: Email string reference
//           SecondaryIndex Email: 0
[CompilerGenerated]
file class IEmailTableRegistration
{
    public class ImplEmailTable : global::BTDB.ODBLayer.RelationDBManipulator<global::Person>, global::IEmailTable
    {
        public ImplEmailTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        ulong global::IEmailTable.GatherByEmail(System.Collections.Generic.ICollection<Person> items, long skip, long take, BTDB.ODBLayer.Constraint<string> email)
        {
            var c_c = new ConstraintInfo[1];
            c_c[0].Constraint = email;
            return GatherBySecondaryKey(0, c_c, items, skip, take, 0u, null);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IEmailTable),
            info => { return transaction => new ImplEmailTable(transaction, info); },
            [typeof(global::Person)]);
    }
}
