//HintName: IContainsIListKeyTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IContainsIListKeyTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: Names global::System.Collections.Generic.IList<string> reference
//           PrimaryIndex: 2

namespace BTDB.GeneratedRelations;
[CompilerGenerated]
file class IContainsIListKeyTableRegistration
{
    [Obsolete("BTDB generated relation implementation type is for BTDB internal use only.")]
    public class ImplContainsIListKeyTable : global::BTDB.ODBLayer.RelationDBManipulator<global::ContainsIListKey>, global::IContainsIListKeyTable
    {
        public ImplContainsIListKeyTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        bool global::IContainsIListKeyTable.Contains(ulong companyId, global::System.Collections.Generic.List<string> names)
        {
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationPKPrefix(ref writer);
            writer.WriteVUInt64(companyId);
            if (names == null) writer.WriteVUInt32(0); else { writer.WriteVUInt32((uint)names.Count); foreach (var item in names) writer.WriteString(item); }
            return base.Contains(writer.GetSpan());
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::IContainsIListKeyTable),
            info => { return transaction => new ImplContainsIListKeyTable(transaction, info); },
            [typeof(global::ContainsIListKey)]);
    }
}
