//HintName: TestNamespace.IStateItemIndexesTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618,SYSLIB0057
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IStateItemIndexesTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: StateGroupId uint
//           PrimaryIndex: 2
// Field: ItemId ulong
//           PrimaryIndex: 3
// Field: Indexes global::System.Collections.Generic.IList<ulong> reference
//           SecondaryIndex Indexes: 0 IncludePrimaryKeyOrder 2

namespace BTDB.GeneratedRelations;
[CompilerGenerated]
file class IStateItemIndexesTableRegistration
{
    [Obsolete("BTDB generated relation implementation type is for BTDB internal use only.")]
    public class ImplStateItemIndexesTable : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.StateItemIndexes>, global::TestNamespace.IStateItemIndexesTable
    {
        public ImplStateItemIndexesTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerable<global::TestNamespace.StateItemIndexes> global::TestNamespace.IStateItemIndexesTable.ListByIndexes(ulong companyId, uint stateGroupId, global::System.Collections.Generic.List<ulong> indexes)
        {
            var remappedSecondaryKeyIndex = RemapPrimeSK(0u);
            var writer = global::BTDB.StreamLayer.MemWriter.CreateFromStackAllocatedSpan(stackalloc byte[512]);
            WriteRelationSKPrefix(ref writer, remappedSecondaryKeyIndex);
            writer.WriteVUInt64(companyId);
            writer.WriteVUInt64(stateGroupId);
            if (indexes == null) writer.WriteVUInt32(0); else { writer.WriteVUInt32((uint)indexes.Count); foreach (var item in indexes) writer.WriteVUInt64(item); }
            return new global::BTDB.ODBLayer.RelationAdvancedSecondaryKeyEnumerator<global::TestNamespace.StateItemIndexes>(this, writer.GetSpan(), remappedSecondaryKeyIndex, 0);
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.IStateItemIndexesTable),
            info => { return transaction => new ImplStateItemIndexesTable(transaction, info); },
            [typeof(global::TestNamespace.StateItemIndexes)]);
    }
}
