//HintName: TestNamespace.IItemTableBase.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IItemTableBase
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: Id ulong
//           PrimaryIndex: 2

namespace TestNamespace;
[CompilerGenerated]
file class IItemTableBaseRegistration
{
    public class ImplItemTableBase : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.Item>, global::TestNamespace.IItemTableBase
    {
        public ImplItemTableBase(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.IItemTableBase),
            info => { return transaction => new ImplItemTableBase(transaction, info); },
            [typeof(global::TestNamespace.Item)]);
    }
}
