//HintName: TestNamespace.IWidgetTable.g.cs
// <auto-generated/>
#pragma warning disable 612,618
#nullable enable
using System;
using System.Runtime.CompilerServices;
using BTDB.ODBLayer;
// Name: IWidgetTable
// Field: CompanyId ulong
//           PrimaryIndex: 1
// Field: ItemId ulong
//           PrimaryIndex: 2

namespace TestNamespace;
[CompilerGenerated]
file class IWidgetTableRegistration
{
    public class ImplWidgetTable : global::BTDB.ODBLayer.RelationDBManipulator<global::TestNamespace.Widget>, global::TestNamespace.IWidgetTable
    {
        public ImplWidgetTable(IObjectDBTransaction transaction, RelationInfo relationInfo) : base(transaction, relationInfo)
        {
        }

        [SkipLocalsInit]
        global::System.Collections.Generic.IEnumerator<global::TestNamespace.Widget> global::TestNamespace.IEnumerableLike<global::TestNamespace.Widget>.GetEnumerator()
        {
            return base.GetEnumerator();
        }
    }
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        BTDB.Serialization.ReflectionMetadata.RegisterRelation(typeof(global::TestNamespace.IWidgetTable),
            info => { return transaction => new ImplWidgetTable(transaction, info); },
            [typeof(global::TestNamespace.Widget)]);
    }
}
