//HintName: Person.g.cs
// <auto-generated/>
#pragma warning disable 612,618
using System;
using System.Runtime.CompilerServices;

[CompilerGenerated]
static file class PersonRegistration
{
    [UnsafeAccessor(UnsafeAccessorKind.Constructor)]
    extern static global::Person Creator();
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
    extern static ref string Field1(global::Person @this);
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "OnBeforeRemove")]
    extern static void OnBeforeRemove1(global::Person @this);
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "SecondOnBeforeRemove")]
    extern static void OnBeforeRemove2(global::Person @this, global::BTDB.ODBLayer.IObjectDBTransaction transaction);
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "ThirdOnBeforeRemove")]
    extern static void OnBeforeRemove3(global::Person @this, global::I3rdPartyInterface dependency, global::I3rdPartyInterface key1);
    [ModuleInitializer]
    internal static unsafe void Register4BTDB()
    {
        global::BTDB.IOC.IContainer.RegisterFactory(typeof(global::Person), (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                var res = new global::Person();
                return res;
            };
        });
        var metadata = new global::BTDB.Serialization.ClassMetadata();
        metadata.Name = "Person";
        metadata.Type = typeof(global::Person);
        metadata.Namespace = "";
        metadata.Implements = [];
        metadata.Creator = &Creator;
        var dummy = Unsafe.As<global::Person>(metadata);
        metadata.Fields = [
            new global::BTDB.Serialization.FieldMetadata
            {
                Name = "Name",
                Type = typeof(string),
                ByteOffset = global::BTDB.Serialization.RawData.CalcOffset(dummy, ref Field1(dummy)),
            },
        ];
        metadata.OnBeforeRemoveFactory = container =>
        {
            global::System.ArgumentNullException.ThrowIfNull(container);
            var f0 = container.CreateFactory(new global::BTDB.IOC.CreateFactoryCtx(), typeof(global::I3rdPartyInterface), "dependency");
            if (f0 == null) throw new global::System.ArgumentException("Cannot resolve global::I3rdPartyInterface dependency parameter of global::Person.ThirdOnBeforeRemove");
            var f1 = container.CreateFactory(new global::BTDB.IOC.CreateFactoryCtx(), typeof(global::I3rdPartyInterface), "key1");
            return (transaction, value) =>
            {
                var val = Unsafe.As<global::Person>(value);
                var res = false;
                res |= OnBeforeRemove1(val);
                res |= OnBeforeRemove2(val, transaction);
                OnBeforeRemove3(val, Unsafe.As<global::I3rdPartyInterface>(f0(container, null))!, f1 != null ? Unsafe.As<global::I3rdPartyInterface>(f1(container, null)) : default(global::I3rdPartyInterface));
                return res;
            };
        };
        metadata.PrimaryKeyFields = [0];
        metadata.IndexOfInKeyValue = 1;
        metadata.SecondaryKeys = [];
        global::BTDB.Serialization.ReflectionMetadata.Register(metadata);
    }
}
