//HintName: TestNamespace.Logger.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;

namespace TestNamespace;

static file class LoggerRegistration
{
    [ModuleInitializer]
    internal static void Init()
    {
        BTDB.IOC.IContainer.RegisterFactory(typeof(global::TestNamespace.Logger).TypeHandle.Value, (container, ctx) =>
        {
            return (container2, ctx2) =>
            {
                return new global::TestNamespace.Logger();
            };
        });
    }
}