//HintName: ErrorHandler.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;

static file class ErrorHandlerRegistration
{
    [ModuleInitializer]
    internal static void Init()
    {
        BTDB.IOC.IContainer.RegisterFactory(typeof(global::ErrorHandler).TypeHandle.Value, (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::ILogger), "logger");
            if (f0 == null) throw new BTDB.KVDBLayer.BTDBException("Cannot resolve ILogger logger parameter of ErrorHandler");
            return (container2, ctx2) =>
            {
                return new global::ErrorHandler(Unsafe.As<global::ILogger>(f0(container2, ctx2)));
            };
        });
    }
}