//HintName: ErrorHandler.g.cs
// <auto-generated/>
using System;
using System.Runtime.CompilerServices;

static file class ErrorHandlerRegistration
{
    [ModuleInitializer]
    internal static void Init()
    {
        BTDB.IOC.IContainer.RegisterFactory(typeof(global::ErrorHandler).TypeHandle.Value, (container, ctx) =>
        {
            var f0 = container.CreateFactory(ctx, typeof(global::ILogger), "Logger");
            if (f0 == null) throw new BTDB.KVDBLayer.BTDBException("Cannot resolve ILogger Logger property of ErrorHandler");
            return (container2, ctx2) =>
            {
                var res = new global::ErrorHandler() { Logger = Unsafe.As<global::ILogger>(f0(container2, ctx2)) };
                return res;
            };
        });
    }
}
