<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../BTDB/BTDB.csproj"/>
        <InternalsVisibleTo Include="BTDB.Replication.Test"/>
        <InternalsVisibleTo Include="BTDB.Replication.Azure"/>
        <InternalsVisibleTo Include="BTDB.Replication.Azure.Test"/>
    </ItemGroup>
</Project>
