variables:
  buildConfiguration: "Release"

jobs:
  - job: "netcore_linux"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UseDotNet@2
        displayName: "Use .NET Core sdk 3.1"
        inputs:
          packageType: sdk
          version: 3.1.x
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        inputs:
          command: build
          arguments: "--configuration $(buildConfiguration)"
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: "**/*Test/*.csproj"
          testRunTitle: Linux
          arguments: "--configuration $(buildConfiguration)"

  - job: "netcore_win"
    pool:
      vmImage: "windows-latest"
    steps:
      - task: UseDotNet@2
        displayName: "Use .NET Core sdk 3.1"
        inputs:
          packageType: sdk
          version: 3.1.x
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        inputs:
          command: build
          arguments: "--configuration $(buildConfiguration)"
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: "**/*Test/*.csproj"
          testRunTitle: Windows
          arguments: "--configuration $(buildConfiguration)"
