variables:
  buildConfiguration: "Release"

jobs:
  - job: "netcore_linux"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UseDotNet@2
        displayName: "Use .NET sdk 5.0"
        inputs:
          packageType: sdk
          version: 5.0.x
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        inputs:
          command: build
          arguments: "-f net5.0 -c $(buildConfiguration)"
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: "**/*Test/*.csproj"
          testRunTitle: Linux
          arguments: "-f net5.0 -c $(buildConfiguration)"

  - job: "netcore_win"
    pool:
      vmImage: "windows-latest"
    steps:
      - task: UseDotNet@2
        displayName: "Use .NET sdk 5.0"
        inputs:
          packageType: sdk
          version: 5.0.x
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        inputs:
          command: build
          arguments: "-f net5.0 -c $(buildConfiguration)"
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: "**/*Test/*.csproj"
          testRunTitle: Windows
          arguments: "-f net5.0 -c $(buildConfiguration)"
