namespace BTDB.KVDBLayer
{
    public enum KVReplayOperation
    {
        Open,
        StartTransaction,
        StartWritingTransaction,
        KeyValueDBDispose,
        TransactionDispose,
        SetKeyPrefix,
        InvalidateCurrentKey,
        FindFirstKey,
        FindLastKey,
        FindPreviousKey,
        FindNextKey,
        FindKey,
        CreateOrUpdateKeyValue,
        GetKeyValueCount,
        GetKeyIndex,
        SetValue,
        EraseCurrent,
        EraseAll,
        EraseRange,
        Commit,
        CalculateStats,
        SetHumanReadableDescriptionInHeader,
        SetKeyIndex,
        GetKey,
        GetValue,
    }
}